import { useQuery } from '@tanstack/react-query';
import { apiBaseUrl, apiClient } from './client';
import { queryKeys } from './queryKeys';

const silent = { silent: true } as const;

/** The generated contracts (`/api/docs`), rebuilt by the server whenever the schema version moves. */
const DOCS_PATHS = {
  openApi: '/api/docs/openapi.json',
  typescript: '/api/docs/typescript',
  playground: 'api/graphql/playground',
} as const;

/** The parts of the OpenAPI document the explorer reads (generated by `schema/codegen/openapi.ts`). */
export type OpenApiParameter = {
  name: string;
  in: 'path' | 'query' | 'header' | 'cookie';
  required?: boolean;
  description?: string;
  schema?: Record<string, unknown>;
};

export type OpenApiOperation = {
  operationId?: string;
  summary?: string;
  tags?: string[];
  parameters?: OpenApiParameter[];
};

export type OpenApiDocument = {
  info: { title: string; version: string };
  tags?: Array<{ name: string; description?: string }>;
  paths: Record<string, Partial<Record<'get' | 'post' | 'put' | 'patch' | 'delete', OpenApiOperation>>>;
};

/** Under `schema.all`: the documents are derived from the schema snapshot. */
const docsKeys = {
  openApi: [...queryKeys.schema.all, 'docs', 'openapi'] as const,
  typescript: [...queryKeys.schema.all, 'docs', 'typescript'] as const,
  playground: ['develop', 'graphqlPlayground'] as const,
};

export const useOpenApiDocument = () =>
  useQuery({
    queryKey: docsKeys.openApi,
    queryFn: () => apiClient.request<OpenApiDocument>(DOCS_PATHS.openApi),
    meta: silent,
  });

export type TypeScriptDeclarations = { schemaVersion: number; source: string };

/** `shapio types generate`'s output for the active schema. */
export const useTypeScriptDeclarations = () =>
  useQuery({
    queryKey: docsKeys.typescript,
    queryFn: () => apiClient.request<TypeScriptDeclarations>(DOCS_PATHS.typescript),
    meta: silent,
  });

/** The vendored GraphiQL page's URL (same origin, so the admin session and CSRF bootstrap apply). */
export const graphqlPlaygroundUrl = () => new URL(DOCS_PATHS.playground, apiBaseUrl()).href;

/** Whether GraphiQL is served (`GRAPHQL_PLAYGROUND_ENABLED`, `GRAPHQL_ENABLED`): 404 when turned off. */
export const useGraphqlPlaygroundAvailable = () =>
  useQuery({
    queryKey: docsKeys.playground,
    queryFn: async () => {
      const response = await fetch(graphqlPlaygroundUrl(), { method: 'HEAD', credentials: 'same-origin' });
      return response.ok;
    },
    staleTime: Infinity,
    meta: silent,
  });
