import { sql, type Kysely } from 'kysely';

/**
 * SQLite baseline: Shapio's whole system schema as of PostgreSQL migration
 * `20261003160000_create_assist_runs`, in one step, with the rows those migrations seed. Later migrations
 * follow the twin rule (`./index.ts`).
 *
 * Written from the migrated PostgreSQL catalog with the type mapping in `db/sqlite/codec.ts`, then kept
 * honest by `test/sqliteBaseline.int.test.ts`, which migrates both databases and compares the logical
 * schema (tables, columns, nullability, defaults, keys, foreign keys, indexes, seed rows). Differences that
 * are deliberate:
 * - UNIQUE constraints are named unique indexes (SQLite only names those in its errors); the three
 *   `NULLS NOT DISTINCT` ones index `coalesce(column, '')` (`db/sqlite/nullsNotDistinct.ts`).
 * - `entry_heads_data_gin` (GIN, containment queries) has no SQLite equivalent and is left out.
 * - The `entry_heads_change_seq` sequence is a row in `sequences`, advanced by `shapio_nextval()`.
 * - `media_assets_folder_id_fkey` sets only `folder_id` to null on delete (PostgreSQL's column list), which
 *   SQLite expresses as a trigger.
 * - `editor_presence` is a plain table (UNLOGGED has no SQLite meaning); the immutability triggers raise.
 * - Identity keys (`outbox_events.id`, `publication_log.id`) are `integer primary key autoincrement`.
 * Defaults call functions Shapio registers on every connection (`db/sqlite/functions.ts`).
 */
const STATEMENTS: readonly string[] = [
  `create table "system_versions" (
    "id" integer_boolean not null default 1,
    "schema_version" integer not null default 0,
    "permissions_version" integer not null default 0,
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "system_versions_id_check" CHECK (id),
    constraint "system_versions_pkey" primary key (id)
  )`,
  `create table "jobs" (
    "id" text_uuid not null default (gen_random_uuid()),
    "type" text not null,
    "payload" text_jsonb not null default ('{}'),
    "status" text not null default ('pending'),
    "priority" integer not null default 0,
    "run_at" text_timestamptz not null default (shapio_now()),
    "attempts" integer not null default 0,
    "max_attempts" integer not null default 10,
    "idempotency_key" text,
    "locked_by" text,
    "locked_until" text_timestamptz,
    "checkpoint" text_jsonb,
    "result" text_jsonb,
    "last_error" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "finished_at" text_timestamptz,
    constraint "jobs_max_attempts_check" CHECK ((max_attempts > 0)),
    constraint "jobs_status_check" CHECK ((status IN ('pending', 'running', 'succeeded', 'dead'))),
    constraint "jobs_pkey" primary key (id)
  )`,
  `create table "outbox_events" (
    "id" integer primary key autoincrement,
    "event_id" text_uuid not null default (gen_random_uuid()),
    "type" text not null,
    "aggregate_type" text not null,
    "aggregate_id" text not null,
    "payload" text_jsonb not null default ('{}'),
    "created_at" text_timestamptz not null default (shapio_now()),
    "dispatched_at" text_timestamptz,
    "dispatch_attempts" integer not null default 0,
    "last_dispatch_error" text,
    "site_id" text_uuid,
    constraint "outbox_events_site_fk" foreign key (site_id) references sites (id) on delete set null
  )`,
  `create unique index "outbox_events_event_id_key" on "outbox_events" (event_id)`,
  `create table "audit_events" (
    "id" text_uuid not null default (gen_random_uuid()),
    "occurred_at" text_timestamptz not null default (shapio_now()),
    "actor_type" text not null,
    "actor_id" text,
    "action" text not null,
    "target_type" text,
    "target_id" text,
    "outcome" text not null,
    "request_id" text,
    "ip" text,
    "metadata" text_jsonb not null default ('{}'),
    "site_id" text_uuid,
    constraint "audit_events_actor_type_check" CHECK ((actor_type IN ('admin', 'app_user', 'token', 'anonymous', 'system'))),
    constraint "audit_events_outcome_check" CHECK ((outcome IN ('success', 'failure'))),
    constraint "audit_events_site_fk" foreign key (site_id) references sites (id) on delete set null,
    constraint "audit_events_pkey" primary key (id)
  )`,
  `create table "admin_users" (
    "id" text_uuid not null default (gen_random_uuid()),
    "email" text not null,
    "name" text not null default (''),
    "password_hash" text not null,
    "status" text not null default ('active'),
    "last_login_at" text_timestamptz,
    "password_changed_at" text_timestamptz not null default (shapio_now()),
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "admin_users_status_check" CHECK ((status IN ('active', 'disabled'))),
    constraint "admin_users_pkey" primary key (id)
  )`,
  `create unique index "admin_users_email_key" on "admin_users" (email)`,
  `create table "admin_roles" (
    "id" text_uuid not null default (gen_random_uuid()),
    "key" text not null,
    "name" text not null,
    "description" text not null default (''),
    "kind" text not null default ('admin'),
    "is_system" integer_boolean not null default 0,
    "version" integer not null default 1,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "admin_roles_key_check" CHECK ((key REGEXP '^[a-z][a-z0-9-]{0,62}$')),
    constraint "admin_roles_kind_check" CHECK ((kind IN ('admin', 'delivery'))),
    constraint "admin_roles_pkey" primary key (id)
  )`,
  `create unique index "admin_roles_key_key" on "admin_roles" (key)`,
  `create table "admin_role_permissions" (
    "id" text_uuid not null default (gen_random_uuid()),
    "role_id" text_uuid not null,
    "action" text not null,
    "model_id" text,
    "condition" text,
    "field_ids" text_array,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "admin_role_permissions_condition_check" CHECK ((condition = 'ownedByPrincipal')),
    constraint "admin_role_permissions_role_id_fkey" foreign key (role_id) references admin_roles (id) on delete cascade,
    constraint "admin_role_permissions_pkey" primary key (id)
  )`,
  `create unique index "admin_role_permissions_grant_uq" on "admin_role_permissions" (role_id, action, coalesce(model_id, ''))`,
  `create table "admin_user_roles" (
    "admin_user_id" text_uuid not null,
    "role_id" text_uuid not null,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid,
    "id" text_uuid not null default (gen_random_uuid()),
    constraint "admin_user_roles_admin_user_id_fkey" foreign key (admin_user_id) references admin_users (id) on delete cascade,
    constraint "admin_user_roles_role_id_fkey" foreign key (role_id) references admin_roles (id) on delete restrict,
    constraint "admin_user_roles_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "admin_user_roles_pk" primary key (id)
  )`,
  `create unique index "admin_user_roles_assignment_uq" on "admin_user_roles" (admin_user_id, role_id, coalesce(site_id, ''))`,
  `create table "admin_sessions" (
    "id" text_uuid not null default (gen_random_uuid()),
    "admin_user_id" text_uuid not null,
    "token_hash" text not null,
    "csrf_secret" text not null,
    "ip" text,
    "user_agent" text,
    "last_seen_at" text_timestamptz not null default (shapio_now()),
    "expires_at" text_timestamptz not null,
    "revoked_at" text_timestamptz,
    "rotation_required" integer_boolean not null default 0,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "admin_sessions_admin_user_id_fkey" foreign key (admin_user_id) references admin_users (id) on delete cascade,
    constraint "admin_sessions_pkey" primary key (id)
  )`,
  `create unique index "admin_sessions_token_hash_key" on "admin_sessions" (token_hash)`,
  `create table "admin_invitations" (
    "id" text_uuid not null default (gen_random_uuid()),
    "email" text not null,
    "token_hash" text,
    "invited_by" text_uuid,
    "expires_at" text_timestamptz not null,
    "accepted_at" text_timestamptz,
    "revoked_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "role_assignments" text_jsonb not null default ('[]'),
    constraint "admin_invitations_invited_by_fkey" foreign key (invited_by) references admin_users (id) on delete set null,
    constraint "admin_invitations_pkey" primary key (id)
  )`,
  `create unique index "admin_invitations_token_hash_key" on "admin_invitations" (token_hash)`,
  `create table "password_resets" (
    "id" text_uuid not null default (gen_random_uuid()),
    "admin_user_id" text_uuid not null,
    "token_hash" text,
    "expires_at" text_timestamptz not null,
    "used_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "password_resets_admin_user_id_fkey" foreign key (admin_user_id) references admin_users (id) on delete cascade,
    constraint "password_resets_pkey" primary key (id)
  )`,
  `create unique index "password_resets_token_hash_key" on "password_resets" (token_hash)`,
  `create table "setup_tokens" (
    "id" text_uuid not null default (gen_random_uuid()),
    "token_hash" text not null,
    "used_at" text_timestamptz,
    "superseded_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "setup_tokens_pkey" primary key (id)
  )`,
  `create unique index "setup_tokens_token_hash_key" on "setup_tokens" (token_hash)`,
  `create table "api_tokens" (
    "id" text_uuid not null default (gen_random_uuid()),
    "name" text not null,
    "token_hash" text not null,
    "token_prefix" text not null,
    "role_id" text_uuid not null,
    "created_by" text_uuid,
    "expires_at" text_timestamptz,
    "last_used_at" text_timestamptz,
    "revoked_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid,
    constraint "api_tokens_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "api_tokens_role_id_fkey" foreign key (role_id) references admin_roles (id) on delete restrict,
    constraint "api_tokens_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "api_tokens_pkey" primary key (id)
  )`,
  `create unique index "api_tokens_token_hash_key" on "api_tokens" (token_hash)`,
  `create table "system_settings" (
    "key" text not null,
    "value" text not null,
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "system_settings_pkey" primary key (key)
  )`,
  `create table "models" (
    "id" text_uuid not null,
    "kind" text not null,
    "api_key" text not null,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "deleted_at" text_timestamptz,
    constraint "models_kind_check" CHECK ((kind IN ('collection', 'singleton', 'component'))),
    constraint "models_pkey" primary key (id)
  )`,
  `create table "schema_revisions" (
    "id" text_uuid not null default (gen_random_uuid()),
    "model_id" text_uuid not null,
    "version" integer not null,
    "definition" text_jsonb not null,
    "hash" text not null,
    "parent_revision_id" text_uuid,
    "created_by_type" text not null,
    "created_by_id" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    constraint "schema_revisions_version_check" CHECK ((version > 0)),
    constraint "schema_revisions_model_id_fkey" foreign key (model_id) references models (id) on delete restrict,
    constraint "schema_revisions_parent_revision_id_fkey" foreign key (parent_revision_id) references schema_revisions (id),
    constraint "schema_revisions_pkey" primary key (id)
  )`,
  `create unique index "schema_revisions_model_version_uq" on "schema_revisions" (model_id, version)`,
  `create table "model_active_versions" (
    "model_id" text_uuid not null,
    "revision_id" text_uuid not null,
    "version" integer not null,
    "schema_version" integer not null,
    "activated_at" text_timestamptz not null default (shapio_now()),
    constraint "model_active_versions_model_id_fkey" foreign key (model_id) references models (id) on delete cascade,
    constraint "model_active_versions_revision_id_fkey" foreign key (revision_id) references schema_revisions (id),
    constraint "model_active_versions_pkey" primary key (model_id)
  )`,
  `create table "schema_change_jobs" (
    "id" text_uuid not null default (gen_random_uuid()),
    "target_type" text not null,
    "target_id" text not null,
    "model_id" text_uuid,
    "from_revision_id" text_uuid,
    "to_revision_id" text_uuid,
    "status" text not null default ('pending'),
    "plan" text_jsonb not null default ('{}'),
    "job_id" text_uuid,
    "error" text_jsonb,
    "requested_by_type" text not null,
    "requested_by_id" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "finished_at" text_timestamptz,
    "change_set_id" text_uuid,
    constraint "schema_change_jobs_status_check" CHECK ((status IN ('pending', 'running', 'activated', 'failed', 'cancelled'))),
    constraint "schema_change_jobs_target_type_check" CHECK ((target_type IN ('model', 'locale'))),
    constraint "schema_change_jobs_change_set_id_fkey" foreign key (change_set_id) references change_sets (id) on delete set null,
    constraint "schema_change_jobs_from_revision_id_fkey" foreign key (from_revision_id) references schema_revisions (id),
    constraint "schema_change_jobs_job_id_fkey" foreign key (job_id) references jobs (id) on delete set null,
    constraint "schema_change_jobs_model_id_fkey" foreign key (model_id) references models (id),
    constraint "schema_change_jobs_to_revision_id_fkey" foreign key (to_revision_id) references schema_revisions (id),
    constraint "schema_change_jobs_pkey" primary key (id)
  )`,
  `create table "locales" (
    "code" text not null,
    "label" text not null,
    "is_default" integer_boolean not null default 0,
    "fallbacks" text_array not null default ('[]'),
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "locales_pkey" primary key (code)
  )`,
  `create table "schema_settings" (
    "id" integer_boolean not null default 1,
    "read_only" integer_boolean not null default 0,
    "read_only_reason" text,
    "updated_by_type" text,
    "updated_by_id" text,
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "schema_settings_id_check" CHECK (id),
    constraint "schema_settings_pkey" primary key (id)
  )`,
  `create table "entries" (
    "id" text_uuid not null default (gen_random_uuid()),
    "model_id" text_uuid not null,
    "owner_app_user_id" text_uuid,
    "created_by_admin_id" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "deleted_at" text_timestamptz,
    "site_id" text_uuid not null,
    constraint "entries_created_by_admin_id_fkey" foreign key (created_by_admin_id) references admin_users (id) on delete set null,
    constraint "entries_model_id_fkey" foreign key (model_id) references models (id) on delete restrict,
    constraint "entries_owner_app_user_fk" foreign key (owner_app_user_id) references app_users (id) on delete set null,
    constraint "entries_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "entries_pkey" primary key (id)
  )`,
  `create unique index "entries_id_site_uq" on "entries" (id, site_id)`,
  `create table "content_revisions" (
    "id" text_uuid not null default (gen_random_uuid()),
    "entry_id" text_uuid not null,
    "locale" text not null,
    "schema_revision_id" text_uuid not null,
    "data" text_jsonb not null,
    "reason" text not null,
    "author_type" text not null,
    "author_id" text,
    "parent_revision_id" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    constraint "content_revisions_reason_check" CHECK ((reason IN ('create', 'save', 'publish', 'restore', 'duplicate', 'localize', 'conversion'))),
    constraint "content_revisions_entry_id_fkey" foreign key (entry_id) references entries (id) on delete restrict,
    constraint "content_revisions_parent_revision_id_fkey" foreign key (parent_revision_id) references content_revisions (id),
    constraint "content_revisions_schema_revision_id_fkey" foreign key (schema_revision_id) references schema_revisions (id),
    constraint "content_revisions_pkey" primary key (id)
  )`,
  `create table "entry_heads" (
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "locale" text not null,
    "state" text not null,
    "revision_id" text_uuid not null,
    "data" text_jsonb not null,
    "autosaved_at" text_timestamptz,
    "version" integer not null default 1,
    "change_seq" bigint not null default (shapio_nextval('entry_heads_change_seq')),
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "entry_heads_state_check" CHECK ((state IN ('draft', 'published'))),
    constraint "entry_heads_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "entry_heads_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "entry_heads_revision_id_fkey" foreign key (revision_id) references content_revisions (id),
    constraint "entry_heads_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "entry_heads_pkey" primary key (entry_id, locale, state)
  )`,
  `create table "relation_edges" (
    "source_entry_id" text_uuid not null,
    "locale" text not null,
    "state" text not null,
    "field_id" text_uuid not null,
    "position" integer not null,
    "target_entry_id" text_uuid not null,
    constraint "relation_edges_head_fk" foreign key (source_entry_id, locale, state) references entry_heads (entry_id, locale, state) on delete cascade,
    constraint "relation_edges_target_entry_id_fkey" foreign key (target_entry_id) references entries (id),
    constraint "relation_edges_pkey" primary key (source_entry_id, locale, state, field_id, "position")
  )`,
  `create table "unique_values" (
    "field_id" text_uuid not null,
    "locale" text not null,
    "state" text not null,
    "value_hash" text not null,
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "site_id" text_uuid not null,
    constraint "unique_values_state_check" CHECK ((state IN ('draft', 'published'))),
    constraint "unique_values_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "unique_values_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "unique_values_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "unique_values_pkey" primary key (site_id, field_id, locale, state, value_hash)
  )`,
  `create table "publication_state" (
    "last_seq" bigint not null default 0,
    "site_id" text_uuid not null,
    constraint "publication_state_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "publication_state_pkey" primary key (site_id)
  )`,
  `create table "publication_log" (
    "id" integer primary key autoincrement,
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "locale" text not null,
    "revision_id" text_uuid not null,
    "from_seq" bigint not null,
    "to_seq" bigint,
    "published_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "publication_log_entry_id_fkey" foreign key (entry_id) references entries (id),
    constraint "publication_log_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete restrict,
    constraint "publication_log_revision_id_fkey" foreign key (revision_id) references content_revisions (id),
    constraint "publication_log_site_fk" foreign key (site_id) references sites (id) on delete restrict
  )`,
  `create table "media_folders" (
    "id" text_uuid not null default (gen_random_uuid()),
    "parent_id" text_uuid,
    "name" text not null,
    "created_by" text_uuid,
    "version" integer not null default 1,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "media_folders_name_check" CHECK (((length(name) >= 1) AND (length(name) <= 255))),
    constraint "media_folders_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "media_folders_parent_id_fkey" foreign key (parent_id, site_id) references media_folders (id, site_id) on delete restrict,
    constraint "media_folders_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "media_folders_pkey" primary key (id)
  )`,
  `create unique index "media_folders_id_site_uq" on "media_folders" (id, site_id)`,
  `create table "media_assets" (
    "id" text_uuid not null,
    "folder_id" text_uuid,
    "storage_driver" text not null,
    "storage_key" text not null,
    "original_filename" text not null,
    "mime_type" text not null,
    "size_bytes" bigint not null,
    "width" integer,
    "height" integer,
    "checksum_sha256" text,
    "alt" text not null default (''),
    "caption" text not null default (''),
    "focal_x" real,
    "focal_y" real,
    "visibility" text not null default ('public'),
    "status" text not null default ('processing'),
    "processing_error" text,
    "created_by" text_uuid,
    "version" integer not null default 1,
    "deleted_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "media_assets_focal_point_ck" CHECK (((focal_x IS NULL) = (focal_y IS NULL))),
    constraint "media_assets_focal_x_check" CHECK (((focal_x >= 0) AND (focal_x <= 1))),
    constraint "media_assets_focal_y_check" CHECK (((focal_y >= 0) AND (focal_y <= 1))),
    constraint "media_assets_status_check" CHECK ((status IN ('processing', 'ready', 'failed'))),
    constraint "media_assets_storage_driver_check" CHECK ((storage_driver IN ('local', 's3'))),
    constraint "media_assets_visibility_check" CHECK ((visibility IN ('public', 'private'))),
    constraint "media_assets_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "media_assets_folder_id_fkey" foreign key (folder_id, site_id) references media_folders (id, site_id),
    constraint "media_assets_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "media_assets_pkey" primary key (id)
  )`,
  `create table "media_variants" (
    "id" text_uuid not null default (gen_random_uuid()),
    "asset_id" text_uuid not null,
    "name" text not null,
    "width" integer,
    "height" integer,
    "format" text not null,
    "mime_type" text not null,
    "storage_key" text,
    "size_bytes" bigint,
    "checksum_sha256" text,
    "status" text not null default ('pending'),
    "error" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "media_variants_status_check" CHECK ((status IN ('pending', 'ready', 'failed'))),
    constraint "media_variants_asset_id_fkey" foreign key (asset_id) references media_assets (id) on delete cascade,
    constraint "media_variants_pkey" primary key (id)
  )`,
  `create unique index "media_variants_asset_name_uq" on "media_variants" (asset_id, name)`,
  `create table "media_references" (
    "asset_id" text_uuid not null,
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "field_id" text not null,
    "locale" text not null,
    "state" text not null,
    "created_at" text_timestamptz not null default (shapio_now()),
    constraint "media_references_state_check" CHECK ((state IN ('draft', 'published'))),
    constraint "media_references_asset_id_fkey" foreign key (asset_id) references media_assets (id) on delete cascade,
    constraint "media_references_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "media_references_pk" primary key (asset_id, entry_id, locale, state, field_id)
  )`,
  `create table "media_upload_grants" (
    "id" text_uuid not null default (gen_random_uuid()),
    "asset_id" text_uuid not null,
    "kind" text not null,
    "storage_driver" text not null,
    "storage_key" text not null,
    "original_filename" text not null,
    "declared_mime_type" text not null,
    "max_size_bytes" bigint not null,
    "folder_id" text_uuid,
    "visibility" text not null,
    "created_by" text_uuid,
    "created_by_principal" text not null,
    "status" text not null default ('pending'),
    "expires_at" text_timestamptz not null,
    "consumed_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "media_upload_grants_kind_check" CHECK ((kind IN ('create', 'replace'))),
    constraint "media_upload_grants_status_check" CHECK ((status IN ('pending', 'consumed', 'rejected', 'expired'))),
    constraint "media_upload_grants_storage_driver_check" CHECK ((storage_driver IN ('local', 's3'))),
    constraint "media_upload_grants_visibility_check" CHECK ((visibility IN ('public', 'private'))),
    constraint "media_upload_grants_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "media_upload_grants_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "media_upload_grants_pkey" primary key (id)
  )`,
  `create unique index "media_upload_grants_storage_key_key" on "media_upload_grants" (storage_key)`,
  `create table "scheduled_publications" (
    "id" text_uuid not null default (gen_random_uuid()),
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "locale" text not null,
    "action" text not null,
    "run_at" text_timestamptz not null,
    "status" text not null default ('scheduled'),
    "created_by_token" text_uuid,
    "job_id" text_uuid,
    "snapshot_seq" bigint,
    "error" text,
    "executed_at" text_timestamptz,
    "created_by" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "scheduled_publications_action_check" CHECK ((action IN ('publish', 'unpublish'))),
    constraint "scheduled_publications_status_check" CHECK ((status IN ('scheduled', 'done', 'failed', 'cancelled'))),
    constraint "scheduled_publications_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "scheduled_publications_created_by_token_fkey" foreign key (created_by_token) references api_tokens (id) on delete set null,
    constraint "scheduled_publications_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "scheduled_publications_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "scheduled_publications_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "scheduled_publications_pkey" primary key (id)
  )`,
  `create table "webhooks" (
    "id" text_uuid not null default (gen_random_uuid()),
    "name" text not null,
    "url" text not null,
    "events" text_array not null default ('[]'),
    "enabled" integer_boolean not null default 1,
    "secret_encrypted" text not null,
    "allow_private_network" integer_boolean not null default 0,
    "max_attempts" integer not null default 8,
    "version" integer not null default 1,
    "created_by" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid,
    constraint "webhooks_max_attempts_check" CHECK (((max_attempts >= 1) AND (max_attempts <= 20))),
    constraint "webhooks_name_check" CHECK (((length(name) >= 1) AND (length(name) <= 200))),
    constraint "webhooks_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "webhooks_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "webhooks_pkey" primary key (id)
  )`,
  `create table "webhook_deliveries" (
    "id" text_uuid not null default (gen_random_uuid()),
    "webhook_id" text_uuid not null,
    "event_id" text_uuid,
    "event_type" text not null,
    "payload" text_jsonb not null,
    "is_test" integer_boolean not null default 0,
    "status" text not null default ('pending'),
    "attempts" integer not null default 0,
    "last_response_status" integer,
    "last_error" text,
    "attempt_log" text_jsonb not null default ('[]'),
    "job_id" text_uuid,
    "delivered_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "webhook_deliveries_status_check" CHECK ((status IN ('pending', 'retrying', 'succeeded', 'dead'))),
    constraint "webhook_deliveries_webhook_id_fkey" foreign key (webhook_id) references webhooks (id) on delete cascade,
    constraint "webhook_deliveries_pkey" primary key (id)
  )`,
  `create table "deployment_connections" (
    "id" text_uuid not null default (gen_random_uuid()),
    "name" text not null,
    "provider" text not null,
    "settings" text_jsonb not null default ('{}'),
    "secrets_encrypted" text not null,
    "secret_env_refs" text_jsonb not null default ('{}'),
    "delivery_role_id" text_uuid,
    "preview_url_template" text,
    "trigger_policy" text_array not null default ('[]'),
    "debounce_seconds" integer not null default 10,
    "allow_private_network" integer_boolean not null default 0,
    "enabled" integer_boolean not null default 1,
    "version" integer not null default 1,
    "created_by" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "deployment_connections_debounce_seconds_check" CHECK (((debounce_seconds >= 0) AND (debounce_seconds <= 3600))),
    constraint "deployment_connections_name_check" CHECK (((length(name) >= 1) AND (length(name) <= 200))),
    constraint "deployment_connections_provider_check" CHECK ((provider IN ('generic_webhook', 'cloudflare_pages', 'vercel', 'netlify', 'github'))),
    constraint "deployment_connections_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "deployment_connections_delivery_role_id_fkey" foreign key (delivery_role_id) references admin_roles (id) on delete set null,
    constraint "deployment_connections_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "deployment_connections_pkey" primary key (id)
  )`,
  `create table "deployment_runs" (
    "id" text_uuid not null default (gen_random_uuid()),
    "connection_id" text_uuid not null,
    "status" text not null default ('queued'),
    "status_rank" integer not null default 0,
    "trigger" text not null,
    "snapshot_seq" bigint,
    "schema_version" integer,
    "retry_of" text_uuid,
    "provider_ref" text,
    "log_url" text,
    "site_url" text,
    "error" text,
    "timeline" text_jsonb not null default ('[]'),
    "job_id" text_uuid,
    "triggered_at" text_timestamptz,
    "finished_at" text_timestamptz,
    "created_by" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "change_set_id" text_uuid,
    constraint "deployment_runs_status_check" CHECK ((status IN ('queued', 'triggered', 'building', 'deployed', 'failed', 'unknown'))),
    constraint "deployment_runs_trigger_check" CHECK ((trigger IN ('publish', 'change_set', 'schema', 'manual', 'retry'))),
    constraint "deployment_runs_change_set_id_fkey" foreign key (change_set_id) references change_sets (id) on delete set null,
    constraint "deployment_runs_connection_id_fkey" foreign key (connection_id) references deployment_connections (id) on delete cascade,
    constraint "deployment_runs_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "deployment_runs_retry_of_fkey" foreign key (retry_of) references deployment_runs (id) on delete set null,
    constraint "deployment_runs_pkey" primary key (id)
  )`,
  `create table "preview_tokens" (
    "id" text_uuid not null default (gen_random_uuid()),
    "token_hash" text not null,
    "token_prefix" text not null,
    "model_id" text_uuid not null,
    "entry_id" text_uuid not null,
    "locale" text,
    "connection_id" text_uuid,
    "delivery_role_id" text_uuid,
    "created_by" text_uuid not null,
    "expires_at" text_timestamptz not null,
    "revoked_at" text_timestamptz,
    "last_used_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "preview_tokens_connection_id_fkey" foreign key (connection_id) references deployment_connections (id) on delete set null,
    constraint "preview_tokens_created_by_fkey" foreign key (created_by) references admin_users (id) on delete cascade,
    constraint "preview_tokens_delivery_role_id_fkey" foreign key (delivery_role_id) references admin_roles (id) on delete set null,
    constraint "preview_tokens_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "preview_tokens_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "preview_tokens_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "preview_tokens_pkey" primary key (id)
  )`,
  `create unique index "preview_tokens_token_hash_key" on "preview_tokens" (token_hash)`,
  `create table "app_users" (
    "id" text_uuid not null default (gen_random_uuid()),
    "email" text not null,
    "name" text not null default (''),
    "password_hash" text,
    "confirmed_at" text_timestamptz,
    "blocked_at" text_timestamptz,
    "last_login_at" text_timestamptz,
    "password_changed_at" text_timestamptz,
    "deleted_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "token_version" integer not null default 0,
    "site_id" text_uuid not null,
    constraint "app_users_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "app_users_pkey" primary key (id)
  )`,
  `create table "app_roles" (
    "id" text_uuid not null default (gen_random_uuid()),
    "key" text not null,
    "name" text not null,
    "description" text not null default (''),
    "is_system" integer_boolean not null default 0,
    "version" integer not null default 1,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "app_roles_key_check" CHECK ((key REGEXP '^[a-z][a-z0-9-]{0,62}$')),
    constraint "app_roles_pkey" primary key (id)
  )`,
  `create unique index "app_roles_key_key" on "app_roles" (key)`,
  `create table "app_role_permissions" (
    "id" text_uuid not null default (gen_random_uuid()),
    "role_id" text_uuid not null,
    "action" text not null,
    "model_id" text,
    "condition" text,
    "field_ids" text_array,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "app_role_permissions_action_check" CHECK ((action IN ('read', 'create', 'update', 'delete', 'publish'))),
    constraint "app_role_permissions_condition_check" CHECK ((condition = 'ownedByPrincipal')),
    constraint "app_role_permissions_role_id_fkey" foreign key (role_id) references app_roles (id) on delete cascade,
    constraint "app_role_permissions_pkey" primary key (id)
  )`,
  `create unique index "app_role_permissions_grant_uq" on "app_role_permissions" (role_id, action, coalesce(model_id, ''))`,
  `create table "app_user_roles" (
    "app_user_id" text_uuid not null,
    "role_id" text_uuid not null,
    "created_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "app_user_roles_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "app_user_roles_role_id_fkey" foreign key (role_id) references app_roles (id) on delete restrict,
    constraint "app_user_roles_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "app_user_roles_pk" primary key (app_user_id, role_id)
  )`,
  `create table "app_refresh_tokens" (
    "id" text_uuid not null default (gen_random_uuid()),
    "app_user_id" text_uuid not null,
    "family_id" text_uuid not null,
    "token_hash" text not null,
    "expires_at" text_timestamptz not null,
    "used_at" text_timestamptz,
    "reuse_grace_used_at" text_timestamptz,
    "revoked_at" text_timestamptz,
    "revoked_reason" text,
    "ip" text,
    "user_agent" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    constraint "app_refresh_tokens_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "app_refresh_tokens_pkey" primary key (id)
  )`,
  `create unique index "app_refresh_tokens_token_hash_key" on "app_refresh_tokens" (token_hash)`,
  `create table "app_oauth_accounts" (
    "id" text_uuid not null default (gen_random_uuid()),
    "app_user_id" text_uuid not null,
    "provider" text not null,
    "provider_user_id" text not null,
    "email" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "app_oauth_accounts_provider_check" CHECK ((provider IN ('google', 'github'))),
    constraint "app_oauth_accounts_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "app_oauth_accounts_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "app_oauth_accounts_pkey" primary key (id)
  )`,
  `create unique index "app_oauth_accounts_identity_uq" on "app_oauth_accounts" (site_id, provider, provider_user_id)`,
  `create table "email_confirmations" (
    "id" text_uuid not null default (gen_random_uuid()),
    "app_user_id" text_uuid not null,
    "email" text not null,
    "token_hash" text,
    "expires_at" text_timestamptz not null,
    "used_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "email_confirmations_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "email_confirmations_pkey" primary key (id)
  )`,
  `create unique index "email_confirmations_token_hash_key" on "email_confirmations" (token_hash)`,
  `create table "app_password_resets" (
    "id" text_uuid not null default (gen_random_uuid()),
    "app_user_id" text_uuid not null,
    "email" text not null,
    "token_hash" text,
    "expires_at" text_timestamptz not null,
    "used_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "app_password_resets_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "app_password_resets_pkey" primary key (id)
  )`,
  `create unique index "app_password_resets_token_hash_key" on "app_password_resets" (token_hash)`,
  `create table "app_login_codes" (
    "id" text_uuid not null default (gen_random_uuid()),
    "app_user_id" text_uuid not null,
    "code_hash" text not null,
    "expires_at" text_timestamptz not null,
    "used_at" text_timestamptz,
    "created_at" text_timestamptz not null default (shapio_now()),
    "code_challenge" text not null,
    constraint "app_login_codes_app_user_id_fkey" foreign key (app_user_id) references app_users (id) on delete cascade,
    constraint "app_login_codes_pkey" primary key (id)
  )`,
  `create unique index "app_login_codes_code_hash_key" on "app_login_codes" (code_hash)`,
  `create table "extension_hook_runs" (
    "event_id" text_uuid not null,
    "hook" text not null,
    "job_id" text_uuid,
    "completed_at" text_timestamptz not null default (shapio_now()),
    constraint "extension_hook_runs_pkey" primary key (event_id, hook)
  )`,
  `create table "field_reads" (
    "day" text_date not null,
    "model_id" text_uuid not null,
    "field_path" text not null,
    "principal_key" text not null,
    "selection" text not null,
    "reads" bigint not null default 0,
    "last_read_at" text_timestamptz not null,
    "site_id" text_uuid not null,
    constraint "field_reads_selection_check" CHECK ((selection IN ('explicit', 'implicit'))),
    constraint "field_reads_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "field_reads_pkey" primary key (day, site_id, model_id, field_path, principal_key, selection)
  )`,
  `create table "token_reads" (
    "day" text_date not null,
    "principal_key" text not null,
    "requests" bigint not null default 0,
    "last_snapshot" bigint,
    "last_read_at" text_timestamptz not null,
    "site_id" text_uuid not null,
    constraint "token_reads_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "token_reads_pkey" primary key (day, site_id, principal_key)
  )`,
  `create table "change_sets" (
    "id" text_uuid not null default (gen_random_uuid()),
    "title" text not null,
    "description" text not null default (''),
    "status" text not null default ('open'),
    "ship_phase" text,
    "source" text not null default ('manual'),
    "restore_of_seq" bigint,
    "scheduled_for" text_timestamptz,
    "schedule_job_id" text_uuid,
    "scheduled_by" text_uuid,
    "scheduled_by_token" text_uuid,
    "ship_job_id" text_uuid,
    "ship_mode" text,
    "ship_requested_by" text_uuid,
    "ship_requested_by_token" text_uuid,
    "acknowledge_breaking" integer_boolean not null default 0,
    "acknowledge_destructive" integer_boolean not null default 0,
    "deployment_connection_id" text_uuid,
    "deployment_run_id" text_uuid,
    "shipped_at" text_timestamptz,
    "shipped_seq" bigint,
    "schema_version_after" integer,
    "error" text_jsonb,
    "restore_report" text_jsonb not null default ('[]'),
    "created_by" text_uuid,
    "created_by_token" text_uuid,
    "version" integer not null default 1,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "change_sets_ship_mode_check" CHECK ((ship_mode IN ('interactive', 'scheduled'))),
    constraint "change_sets_ship_phase_check" CHECK ((ship_phase IN ('preparing', 'activating'))),
    constraint "change_sets_source_check" CHECK ((source IN ('manual', 'release', 'restore', 'builder', 'assist'))),
    constraint "change_sets_status_check" CHECK ((status IN ('open', 'scheduled', 'shipping', 'shipped', 'failed', 'discarded'))),
    constraint "change_sets_title_check" CHECK (((length(title) >= 1) AND (length(title) <= 200))),
    constraint "change_sets_created_by_fkey" foreign key (created_by) references admin_users (id) on delete set null,
    constraint "change_sets_created_by_token_fkey" foreign key (created_by_token) references api_tokens (id) on delete set null,
    constraint "change_sets_deployment_connection_id_fkey" foreign key (deployment_connection_id) references deployment_connections (id) on delete set null,
    constraint "change_sets_deployment_run_id_fkey" foreign key (deployment_run_id) references deployment_runs (id) on delete set null,
    constraint "change_sets_scheduled_by_fkey" foreign key (scheduled_by) references admin_users (id) on delete set null,
    constraint "change_sets_scheduled_by_token_fkey" foreign key (scheduled_by_token) references api_tokens (id) on delete set null,
    constraint "change_sets_ship_requested_by_fkey" foreign key (ship_requested_by) references admin_users (id) on delete set null,
    constraint "change_sets_ship_requested_by_token_fkey" foreign key (ship_requested_by_token) references api_tokens (id) on delete set null,
    constraint "change_sets_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "change_sets_pkey" primary key (id)
  )`,
  `create unique index "change_sets_id_site_uq" on "change_sets" (id, site_id)`,
  `create table "schema_drafts" (
    "id" text_uuid not null default (gen_random_uuid()),
    "change_set_id" text_uuid not null,
    "definition_id" text_uuid not null,
    "kind" text not null,
    "api_key" text not null,
    "base_version" integer,
    "definition" text_jsonb,
    "version" integer not null default 1,
    "updated_by_type" text not null,
    "updated_by_id" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "schema_drafts_kind_check" CHECK ((kind IN ('collection', 'singleton', 'component'))),
    constraint "schema_drafts_change_set_id_fkey" foreign key (change_set_id) references change_sets (id) on delete cascade,
    constraint "schema_drafts_pkey" primary key (id)
  )`,
  `create unique index "schema_drafts_set_definition_uq" on "schema_drafts" (change_set_id, definition_id)`,
  `create table "change_set_items" (
    "id" text_uuid not null default (gen_random_uuid()),
    "change_set_id" text_uuid not null,
    "kind" text not null,
    "position" integer not null,
    "entry_id" text_uuid,
    "model_id" text_uuid,
    "locale" text,
    "action" text,
    "source_revision_id" text_uuid,
    "schema_draft_id" text_uuid,
    "status" text not null default ('pending'),
    "error" text,
    "ship_state" text_jsonb,
    "created_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "change_set_items_action_check" CHECK ((action IN ('publish', 'unpublish'))),
    constraint "change_set_items_kind_check" CHECK ((kind IN ('entry', 'schema'))),
    constraint "change_set_items_shape_check" CHECK ((((kind = 'entry') AND (entry_id IS NOT NULL) AND (model_id IS NOT NULL) AND (locale IS NOT NULL) AND (action IS NOT NULL) AND (schema_draft_id IS NULL)) OR ((kind = 'schema') AND (schema_draft_id IS NOT NULL) AND (entry_id IS NULL) AND (source_revision_id IS NULL)))),
    constraint "change_set_items_status_check" CHECK ((status IN ('pending', 'done', 'failed'))),
    constraint "change_set_items_change_set_id_fkey" foreign key (change_set_id) references change_sets (id) on delete cascade,
    constraint "change_set_items_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "change_set_items_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "change_set_items_schema_draft_id_fkey" foreign key (schema_draft_id) references schema_drafts (id) on delete cascade,
    constraint "change_set_items_set_site_fk" foreign key (change_set_id, site_id) references change_sets (id, site_id) on delete cascade,
    constraint "change_set_items_source_revision_id_fkey" foreign key (source_revision_id) references content_revisions (id),
    constraint "change_set_items_pkey" primary key (id)
  )`,
  `create table "publication_snapshots" (
    "seq" bigint not null,
    "schema_version" integer,
    "source" text not null,
    "change_set_id" text_uuid,
    "actor_type" text,
    "actor_id" text,
    "created_at" text_timestamptz not null default (shapio_now()),
    "site_id" text_uuid not null,
    constraint "publication_snapshots_change_set_id_fkey" foreign key (change_set_id) references change_sets (id) on delete set null,
    constraint "publication_snapshots_site_fk" foreign key (site_id) references sites (id) on delete cascade,
    constraint "publication_snapshots_pkey" primary key (site_id, seq)
  )`,
  `create table "editor_presence" (
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "admin_user_id" text_uuid not null,
    "tab_id" text not null,
    "locale" text,
    "started_at" text_timestamptz not null default (shapio_now()),
    "last_seen_at" text_timestamptz not null default (shapio_now()),
    constraint "editor_presence_tab_id_check" CHECK (((length(tab_id) >= 1) AND (length(tab_id) <= 64))),
    constraint "editor_presence_pkey" primary key (entry_id, admin_user_id, tab_id)
  )`,
  `create table "content_health_findings" (
    "id" text_uuid not null default (gen_random_uuid()),
    "entry_id" text_uuid not null,
    "model_id" text_uuid not null,
    "locale" text not null,
    "rule" text not null,
    "subject" text not null default (''),
    "severity" text not null,
    "path" text,
    "details" text_jsonb not null default ('{}'),
    "first_seen_at" text_timestamptz not null default (shapio_now()),
    "last_seen_at" text_timestamptz not null default (shapio_now()),
    "resolved_at" text_timestamptz,
    "site_id" text_uuid not null,
    constraint "content_health_findings_severity_check" CHECK ((severity IN ('error', 'warning'))),
    constraint "content_health_findings_entry_id_fkey" foreign key (entry_id) references entries (id) on delete cascade,
    constraint "content_health_findings_entry_site_fk" foreign key (entry_id, site_id) references entries (id, site_id) on delete cascade,
    constraint "content_health_findings_site_fk" foreign key (site_id) references sites (id) on delete restrict,
    constraint "content_health_findings_pkey" primary key (id)
  )`,
  `create unique index "content_health_findings_entry_id_locale_rule_subject_key" on "content_health_findings" (entry_id, locale, rule, subject)`,
  `create table "sites" (
    "id" text_uuid not null default (gen_random_uuid()),
    "key" text not null,
    "name" text not null,
    "is_primary" integer_boolean not null default 0,
    "version" integer not null default 1,
    "created_at" text_timestamptz not null default (shapio_now()),
    "updated_at" text_timestamptz not null default (shapio_now()),
    constraint "sites_key_check" CHECK ((key REGEXP '^[a-z][a-z0-9-]{0,62}$')),
    constraint "sites_name_check" CHECK (((length(name) >= 1) AND (length(name) <= 200))),
    constraint "sites_pkey" primary key (id)
  )`,
  `create unique index "sites_key_key" on "sites" (key)`,
  `create table "site_app_roles" (
    "site_id" text_uuid not null,
    "audience" text not null,
    "role_id" text_uuid not null,
    "created_at" text_timestamptz not null default (shapio_now()),
    constraint "site_app_roles_audience_check" CHECK ((audience IN ('public', 'authenticated'))),
    constraint "site_app_roles_role_id_fkey" foreign key (role_id) references app_roles (id) on delete cascade,
    constraint "site_app_roles_site_id_fkey" foreign key (site_id) references sites (id) on delete cascade,
    constraint "site_app_roles_pkey" primary key (site_id, audience, role_id)
  )`,
  `create table "assist_runs" (
    "id" text_uuid not null default (gen_random_uuid()),
    "site_id" text_uuid not null,
    "actor_type" text not null,
    "actor_id" text not null,
    "action" text not null,
    "rule" text,
    "provider" text not null,
    "model" text not null,
    "input_tokens" integer not null default 0,
    "output_tokens" integer not null default 0,
    "duration_ms" integer not null default 0,
    "status" text not null,
    "error_code" text,
    "job_id" text_uuid,
    "created_at" text_timestamptz not null default (shapio_now()),
    "finished_at" text_timestamptz,
    constraint "assist_runs_action_check" CHECK ((action IN ('alt_text', 'summarize', 'translate', 'rewrite', 'schema_draft', 'content_ops'))),
    constraint "assist_runs_status_check" CHECK ((status IN ('queued', 'running', 'succeeded', 'failed'))),
    constraint "assist_runs_job_id_fkey" foreign key (job_id) references jobs (id) on delete set null,
    constraint "assist_runs_site_id_fkey" foreign key (site_id) references sites (id) on delete cascade,
    constraint "assist_runs_pkey" primary key (id)
  )`,
  `create index "admin_invitations_pending_email_idx" on "admin_invitations" (email) where ((accepted_at IS NULL) AND (revoked_at IS NULL))`,
  `create index "admin_sessions_user_idx" on "admin_sessions" (admin_user_id) where (revoked_at IS NULL)`,
  `create index "admin_user_roles_role_idx" on "admin_user_roles" (role_id)`,
  `create index "api_tokens_role_idx" on "api_tokens" (role_id)`,
  `create index "app_oauth_accounts_user_idx" on "app_oauth_accounts" (app_user_id)`,
  `create index "app_password_resets_user_idx" on "app_password_resets" (app_user_id)`,
  `create index "app_refresh_tokens_family_idx" on "app_refresh_tokens" (family_id)`,
  `create index "app_refresh_tokens_user_idx" on "app_refresh_tokens" (app_user_id) where (revoked_at IS NULL)`,
  `create index "app_user_roles_role_idx" on "app_user_roles" (role_id)`,
  `create index "app_users_created_idx" on "app_users" (site_id, created_at DESC, id DESC) where (deleted_at IS NULL)`,
  `create unique index "app_users_email_uq" on "app_users" (site_id, lower(email)) where (deleted_at IS NULL)`,
  `create index "assist_runs_created_idx" on "assist_runs" (created_at)`,
  `create index "assist_runs_site_created_idx" on "assist_runs" (site_id, created_at)`,
  `create index "audit_events_actor_idx" on "audit_events" (actor_type, actor_id, occurred_at DESC)`,
  `create index "audit_events_occurred_at_idx" on "audit_events" (occurred_at DESC)`,
  `create index "audit_events_target_idx" on "audit_events" (target_type, target_id, occurred_at DESC)`,
  `create unique index "change_set_items_draft_uq" on "change_set_items" (schema_draft_id)`,
  `create index "change_set_items_entry_idx" on "change_set_items" (entry_id) where (entry_id IS NOT NULL)`,
  `create unique index "change_set_items_entry_uq" on "change_set_items" (change_set_id, entry_id, locale) where (kind = 'entry')`,
  `create index "change_set_items_set_idx" on "change_set_items" (change_set_id, position)`,
  `create index "change_sets_status_idx" on "change_sets" (site_id, status, created_at DESC)`,
  `create index "content_health_findings_open_idx" on "content_health_findings" (site_id, rule, last_seen_at DESC, id) where (resolved_at IS NULL)`,
  `create index "content_health_findings_resolved_idx" on "content_health_findings" (resolved_at) where (resolved_at IS NOT NULL)`,
  `create index "content_revisions_entry_idx" on "content_revisions" (entry_id, locale, created_at)`,
  `create index "deployment_runs_connection_idx" on "deployment_runs" (connection_id, created_at DESC)`,
  `create unique index "deployment_runs_queued_uq" on "deployment_runs" (connection_id) where (status = 'queued')`,
  `create index "editor_presence_model_idx" on "editor_presence" (model_id, last_seen_at)`,
  `create index "editor_presence_seen_idx" on "editor_presence" (last_seen_at)`,
  `create index "email_confirmations_user_idx" on "email_confirmations" (app_user_id)`,
  `create index "entries_model_idx" on "entries" (site_id, model_id, created_at) where (deleted_at IS NULL)`,
  `create index "entries_owner_idx" on "entries" (owner_app_user_id) where (owner_app_user_id IS NOT NULL)`,
  `create index "entry_heads_change_seq_idx" on "entry_heads" (model_id, change_seq)`,
  `create index "entry_heads_model_locale_state_idx" on "entry_heads" (site_id, model_id, locale, state)`,
  `create index "field_reads_model_day_idx" on "field_reads" (model_id, day)`,
  `create unique index "jobs_idempotency_key_uq" on "jobs" (idempotency_key) where (idempotency_key IS NOT NULL)`,
  `create index "jobs_pending_idx" on "jobs" (priority DESC, run_at) where (status = 'pending')`,
  `create index "jobs_running_lease_idx" on "jobs" (locked_until) where (status = 'running')`,
  `create unique index "locales_single_default_uq" on "locales" (is_default) where is_default`,
  `create index "media_assets_created_idx" on "media_assets" (site_id, created_at, id) where (deleted_at IS NULL)`,
  `create index "media_assets_driver_idx" on "media_assets" (storage_driver, id)`,
  `create index "media_assets_folder_idx" on "media_assets" (folder_id, created_at, id) where (deleted_at IS NULL)`,
  `create unique index "media_assets_storage_key_uq" on "media_assets" (storage_key)`,
  `create unique index "media_folders_sibling_name_uq" on "media_folders" (site_id, COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'), lower(name))`,
  `create index "media_references_entry_idx" on "media_references" (entry_id, locale, state)`,
  `create unique index "media_variants_storage_key_uq" on "media_variants" (storage_key)`,
  `create unique index "models_api_key_uq" on "models" (lower(api_key)) where (deleted_at IS NULL)`,
  `create index "outbox_events_undispatched_idx" on "outbox_events" (id) where (dispatched_at IS NULL)`,
  `create index "password_resets_user_idx" on "password_resets" (admin_user_id)`,
  `create index "preview_tokens_entry_idx" on "preview_tokens" (entry_id, created_at DESC)`,
  `create index "publication_log_entry_locale_from_idx" on "publication_log" (entry_id, locale, from_seq)`,
  `create index "publication_log_model_seq_idx" on "publication_log" (site_id, model_id, from_seq)`,
  `create unique index "publication_log_open_uq" on "publication_log" (entry_id, locale) where (to_seq IS NULL)`,
  `create index "publication_log_to_seq_idx" on "publication_log" (site_id, to_seq) where (to_seq IS NOT NULL)`,
  `create index "publication_snapshots_change_set_idx" on "publication_snapshots" (change_set_id) where (change_set_id IS NOT NULL)`,
  `create index "relation_edges_target_idx" on "relation_edges" (target_entry_id, state)`,
  `create index "scheduled_publications_entry_idx" on "scheduled_publications" (entry_id, locale)`,
  `create index "scheduled_publications_site_idx" on "scheduled_publications" (site_id, run_at)`,
  `create index "scheduled_publications_status_idx" on "scheduled_publications" (status, run_at)`,
  `create index "schema_change_jobs_change_set_idx" on "schema_change_jobs" (change_set_id) where (change_set_id IS NOT NULL)`,
  `create unique index "schema_change_jobs_in_flight_uq" on "schema_change_jobs" (target_type, target_id) where (status IN ('pending', 'running'))`,
  `create index "schema_change_jobs_model_idx" on "schema_change_jobs" (model_id, created_at DESC)`,
  `create index "schema_drafts_definition_idx" on "schema_drafts" (definition_id)`,
  `create index "site_app_roles_role_idx" on "site_app_roles" (role_id)`,
  `create unique index "sites_single_primary_uq" on "sites" (is_primary) where is_primary`,
  `create index "unique_values_entry_idx" on "unique_values" (entry_id)`,
  `create unique index "webhook_deliveries_event_uq" on "webhook_deliveries" (webhook_id, event_id) where (event_id IS NOT NULL)`,
  `create index "webhook_deliveries_webhook_idx" on "webhook_deliveries" (webhook_id, created_at DESC)`,
  `create trigger "media_assets_folder_id_fkey_set_null" before delete on "media_folders" for each row begin update "media_assets" set folder_id = null where folder_id = old.id and site_id = old.site_id; end`,
  `create table "sequences" (
    "name" text primary key,
    "value" integer not null default 0
  )`,
  `insert into "sequences" (name, value) values ('entry_heads_change_seq', 0)`,
  `create trigger "schema_revisions_no_update" before update on "schema_revisions" for each row begin select raise(abort, 'schema_revisions rows are immutable'); end`,
  `create trigger "content_revisions_no_update" before update on "content_revisions" for each row begin select raise(abort, 'content_revisions rows are immutable'); end`,
  `insert into system_versions default values`,
  `insert into schema_settings default values`,
  `insert into locales (code, label, is_default) values ('en', 'English', 1)`,
  `insert into sites (id, key, name, is_primary) values ('00000000-0000-4000-b000-000000000001', 'default', 'Default site', 1)`,
  `insert into publication_state (site_id, last_seq) values ('00000000-0000-4000-b000-000000000001', 0)`,
  `insert into app_roles (id, key, name, description, is_system) values
    ('00000000-0000-4000-a000-000000000001', 'public', 'Public', 'Applies to every caller without a token. Grants nothing until you add permissions.', 1),
    ('00000000-0000-4000-a000-000000000002', 'authenticated', 'Authenticated', 'Held by every signed-in app user, in addition to their custom roles. Grants nothing until you add permissions.', 1)`,
  `insert into site_app_roles (site_id, audience, role_id) values
    ('00000000-0000-4000-b000-000000000001', 'public', '00000000-0000-4000-a000-000000000001'),
    ('00000000-0000-4000-b000-000000000001', 'authenticated', '00000000-0000-4000-a000-000000000002')`,
];

const TABLES: readonly string[] = [
  'system_versions',
  'jobs',
  'outbox_events',
  'audit_events',
  'admin_users',
  'admin_roles',
  'admin_role_permissions',
  'admin_user_roles',
  'admin_sessions',
  'admin_invitations',
  'password_resets',
  'setup_tokens',
  'api_tokens',
  'system_settings',
  'models',
  'schema_revisions',
  'model_active_versions',
  'schema_change_jobs',
  'locales',
  'schema_settings',
  'entries',
  'content_revisions',
  'entry_heads',
  'relation_edges',
  'unique_values',
  'publication_state',
  'publication_log',
  'media_folders',
  'media_assets',
  'media_variants',
  'media_references',
  'media_upload_grants',
  'scheduled_publications',
  'webhooks',
  'webhook_deliveries',
  'deployment_connections',
  'deployment_runs',
  'preview_tokens',
  'app_users',
  'app_roles',
  'app_role_permissions',
  'app_user_roles',
  'app_refresh_tokens',
  'app_oauth_accounts',
  'email_confirmations',
  'app_password_resets',
  'app_login_codes',
  'extension_hook_runs',
  'field_reads',
  'token_reads',
  'change_sets',
  'schema_drafts',
  'change_set_items',
  'publication_snapshots',
  'editor_presence',
  'content_health_findings',
  'sites',
  'site_app_roles',
  'assist_runs',
  'sequences',
];

export const up = async (db: Kysely<unknown>): Promise<void> => {
  for (const statement of STATEMENTS) {
    await sql.raw(statement).execute(db);
  }
};

export const down = async (db: Kysely<unknown>): Promise<void> => {
  // Foreign keys reference in cycles; checking them at commit lets the tables drop in any order.
  await sql`pragma defer_foreign_keys = on`.execute(db);
  for (const table of [...TABLES].reverse()) {
    await sql.raw(`drop table if exists "${table}"`).execute(db);
  }
};
