/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ContentData } from "./contentData.js";
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminInvitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string | null;
  revoked_at: Timestamp | null;
  role_assignments: Generated<Json>;
  token_hash: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AdminRolePermissions {
  action: string;
  condition: string | null;
  created_at: Generated<Timestamp>;
  field_ids: string[] | null;
  id: Generated<string>;
  model_id: string | null;
  role_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AdminRoles {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  is_system: Generated<boolean>;
  key: string;
  kind: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AdminSessions {
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  csrf_secret: string;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  rotation_required: Generated<boolean>;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
}

export interface AdminUserRoles {
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role_id: string;
  site_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AdminUsers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  name: Generated<string>;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ApiTokens {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  revoked_at: Timestamp | null;
  role_id: string;
  site_id: string | null;
  token_hash: string;
  token_prefix: string;
  updated_at: Generated<Timestamp>;
}

export interface AppLoginCodes {
  app_user_id: string;
  code_challenge: string;
  code_hash: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  used_at: Timestamp | null;
}

export interface AppOauthAccounts {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  provider: string;
  provider_user_id: string;
  site_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AppPasswordResets {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string | null;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface AppRefreshTokens {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip: string | null;
  reuse_grace_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  token_hash: string;
  used_at: Timestamp | null;
  user_agent: string | null;
}

export interface AppRolePermissions {
  action: string;
  condition: string | null;
  created_at: Generated<Timestamp>;
  field_ids: string[] | null;
  id: Generated<string>;
  model_id: string | null;
  role_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AppRoles {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  is_system: Generated<boolean>;
  key: string;
  name: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AppUserRoles {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  role_id: string;
  site_id: string;
}

export interface AppUsers {
  blocked_at: Timestamp | null;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  name: Generated<string>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  site_id: string;
  token_version: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface AssistRuns {
  action: string;
  actor_id: string;
  actor_type: string;
  created_at: Generated<Timestamp>;
  duration_ms: Generated<number>;
  error_code: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input_tokens: Generated<number>;
  job_id: string | null;
  model: string;
  output_tokens: Generated<number>;
  provider: string;
  rule: string | null;
  site_id: string;
  status: string;
}

export interface AuditEvents {
  action: string;
  actor_id: string | null;
  actor_type: string;
  id: Generated<string>;
  ip: string | null;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  outcome: string;
  request_id: string | null;
  seq: Generated<Int8>;
  site_id: string | null;
  target_id: string | null;
  target_type: string | null;
}

export interface ChangeSetItems {
  action: string | null;
  change_set_id: string;
  created_at: Generated<Timestamp>;
  entry_id: string | null;
  error: string | null;
  id: Generated<string>;
  kind: string;
  locale: string | null;
  model_id: string | null;
  position: number;
  schema_draft_id: string | null;
  ship_state: Json | null;
  site_id: string;
  source_revision_id: string | null;
  status: Generated<string>;
}

export interface ChangeSets {
  acknowledge_breaking: Generated<boolean>;
  acknowledge_destructive: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  created_by_token: string | null;
  deployment_connection_id: string | null;
  deployment_run_id: string | null;
  description: Generated<string>;
  error: Json | null;
  id: Generated<string>;
  restore_of_seq: Int8 | null;
  restore_report: Generated<Json>;
  schedule_job_id: string | null;
  scheduled_by: string | null;
  scheduled_by_token: string | null;
  scheduled_for: Timestamp | null;
  schema_version_after: number | null;
  ship_job_id: string | null;
  ship_mode: string | null;
  ship_phase: string | null;
  ship_requested_by: string | null;
  ship_requested_by_token: string | null;
  shipped_at: Timestamp | null;
  shipped_seq: Int8 | null;
  site_id: string;
  source: Generated<string>;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ContentHealthFindings {
  details: Generated<Json>;
  entry_id: string;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  locale: string;
  model_id: string;
  path: string | null;
  resolved_at: Timestamp | null;
  rule: string;
  severity: string;
  site_id: string;
  subject: Generated<string>;
}

export interface ContentRevisions {
  author_id: string | null;
  author_type: string;
  created_at: Generated<Timestamp>;
  data: ContentData;
  entry_id: string;
  id: Generated<string>;
  locale: string;
  parent_revision_id: string | null;
  reason: string;
  schema_revision_id: string;
}

export interface DeploymentConnections {
  allow_private_network: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  debounce_seconds: Generated<number>;
  delivery_role_id: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  name: string;
  preview_url_template: string | null;
  provider: string;
  secret_env_refs: Generated<Json>;
  secrets_encrypted: string;
  settings: Generated<Json>;
  site_id: string;
  trigger_policy: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DeploymentRuns {
  change_set_id: string | null;
  connection_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  job_id: string | null;
  log_url: string | null;
  provider_ref: string | null;
  retry_of: string | null;
  schema_version: number | null;
  site_url: string | null;
  snapshot_seq: Int8 | null;
  status: Generated<string>;
  status_rank: Generated<number>;
  timeline: Generated<Json>;
  trigger: string;
  triggered_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface EditorPresence {
  admin_user_id: string;
  entry_id: string;
  last_seen_at: Generated<Timestamp>;
  locale: string | null;
  model_id: string;
  started_at: Generated<Timestamp>;
  tab_id: string;
}

export interface EmailConfirmations {
  app_user_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string | null;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface Entries {
  created_at: Generated<Timestamp>;
  created_by_admin_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  model_id: string;
  owner_app_user_id: string | null;
  site_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EntryHeads {
  autosaved_at: Timestamp | null;
  change_seq: Generated<Int8>;
  created_at: Generated<Timestamp>;
  data: ContentData;
  entry_id: string;
  locale: string;
  model_id: string;
  revision_id: string;
  site_id: string;
  state: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ExtensionHookRuns {
  completed_at: Generated<Timestamp>;
  event_id: string;
  hook: string;
  job_id: string | null;
}

export interface FieldReads {
  day: Timestamp;
  field_path: string;
  last_read_at: Timestamp;
  model_id: string;
  principal_key: string;
  reads: Generated<Int8>;
  selection: string;
  site_id: string;
}

export interface Jobs {
  attempts: Generated<number>;
  checkpoint: Json | null;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string | null;
  last_error: string | null;
  locked_by: string | null;
  locked_until: Timestamp | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  priority: Generated<number>;
  result: Json | null;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Locales {
  code: string;
  created_at: Generated<Timestamp>;
  fallbacks: Generated<string[]>;
  is_default: Generated<boolean>;
  label: string;
  updated_at: Generated<Timestamp>;
}

export interface MediaAssets {
  alt: Generated<string>;
  caption: Generated<string>;
  checksum_sha256: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  focal_x: number | null;
  focal_y: number | null;
  folder_id: string | null;
  height: number | null;
  id: string;
  mime_type: string;
  original_filename: string;
  processing_error: string | null;
  site_id: string;
  size_bytes: Int8;
  status: Generated<string>;
  storage_driver: string;
  storage_key: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  visibility: Generated<string>;
  width: number | null;
}

export interface MediaFolders {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  parent_id: string | null;
  site_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface MediaReferences {
  asset_id: string;
  created_at: Generated<Timestamp>;
  entry_id: string;
  field_id: string;
  locale: string;
  model_id: string;
  state: string;
}

export interface MediaUploadGrants {
  asset_id: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  created_by_principal: string;
  declared_mime_type: string;
  expires_at: Timestamp;
  folder_id: string | null;
  id: Generated<string>;
  kind: string;
  max_size_bytes: Int8;
  original_filename: string;
  site_id: string;
  status: Generated<string>;
  storage_driver: string;
  storage_key: string;
  visibility: string;
}

export interface MediaVariants {
  asset_id: string;
  checksum_sha256: string | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  format: string;
  height: number | null;
  id: Generated<string>;
  mime_type: string;
  name: string;
  size_bytes: Int8 | null;
  status: Generated<string>;
  storage_key: string | null;
  updated_at: Generated<Timestamp>;
  width: number | null;
}

export interface ModelActiveVersions {
  activated_at: Generated<Timestamp>;
  model_id: string;
  revision_id: string;
  schema_version: number;
  version: number;
}

export interface Models {
  api_key: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  kind: string;
  site_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  created_at: Generated<Timestamp>;
  dispatch_attempts: Generated<number>;
  dispatched_at: Timestamp | null;
  event_id: Generated<string>;
  id: Generated<Int8>;
  last_dispatch_error: string | null;
  payload: Generated<Json>;
  site_id: string | null;
  type: string;
}

export interface PasswordResets {
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string | null;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface PreviewTokens {
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  delivery_role_id: string | null;
  entry_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  locale: string | null;
  model_id: string;
  revoked_at: Timestamp | null;
  site_id: string;
  token_hash: string;
  token_prefix: string;
}

export interface PublicationLog {
  entry_id: string;
  from_seq: Int8;
  id: Generated<Int8>;
  locale: string;
  model_id: string;
  published_at: Generated<Timestamp>;
  revision_id: string;
  site_id: string;
  to_seq: Int8 | null;
}

export interface PublicationSnapshots {
  actor_id: string | null;
  actor_type: string | null;
  change_set_id: string | null;
  created_at: Generated<Timestamp>;
  schema_version: number | null;
  seq: Int8;
  site_id: string;
  source: string;
}

export interface PublicationState {
  last_seq: Generated<Int8>;
  site_id: string;
}

export interface RelationEdges {
  field_id: string;
  locale: string;
  position: number;
  source_entry_id: string;
  state: string;
  target_entry_id: string;
}

export interface ScheduledPublications {
  action: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  created_by_token: string | null;
  entry_id: string;
  error: string | null;
  executed_at: Timestamp | null;
  id: Generated<string>;
  job_id: string | null;
  locale: string;
  model_id: string;
  run_at: Timestamp;
  site_id: string;
  snapshot_seq: Int8 | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface SchemaChangeJobs {
  change_set_id: string | null;
  created_at: Generated<Timestamp>;
  error: Json | null;
  finished_at: Timestamp | null;
  from_revision_id: string | null;
  id: Generated<string>;
  job_id: string | null;
  model_id: string | null;
  plan: Generated<Json>;
  requested_by_id: string | null;
  requested_by_type: string;
  status: Generated<string>;
  target_id: string;
  target_type: string;
  to_revision_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SchemaDrafts {
  api_key: string;
  base_version: number | null;
  change_set_id: string;
  created_at: Generated<Timestamp>;
  definition: Json | null;
  definition_id: string;
  id: Generated<string>;
  kind: string;
  shared: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
  updated_by_type: string;
  version: Generated<number>;
}

export interface SchemaRevisions {
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  created_by_type: string;
  definition: Json;
  hash: string;
  id: Generated<string>;
  model_id: string;
  parent_revision_id: string | null;
  version: number;
}

export interface SchemaSettings {
  id: Generated<boolean>;
  read_only: Generated<boolean>;
  read_only_reason: string | null;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
  updated_by_type: string | null;
}

export interface SetupTokens {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  superseded_at: Timestamp | null;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface SiteAppRoles {
  audience: string;
  created_at: Generated<Timestamp>;
  role_id: string;
  site_id: string;
}

export interface Sites {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  key: string;
  name: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface SystemSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface SystemVersions {
  id: Generated<boolean>;
  permissions_version: Generated<number>;
  schema_version: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface TokenReads {
  day: Timestamp;
  last_read_at: Timestamp;
  last_snapshot: Int8 | null;
  principal_key: string;
  requests: Generated<Int8>;
  site_id: string;
}

export interface UniqueValues {
  entry_id: string;
  field_id: string;
  locale: string;
  model_id: string;
  site_id: string;
  state: string;
  value_hash: string;
}

export interface WebhookDeliveries {
  attempt_log: Generated<Json>;
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event_id: string | null;
  event_type: string;
  id: Generated<string>;
  is_test: Generated<boolean>;
  job_id: string | null;
  last_error: string | null;
  last_response_status: number | null;
  payload: Json;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  webhook_id: string;
}

export interface Webhooks {
  allow_private_network: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  enabled: Generated<boolean>;
  events: Generated<string[]>;
  id: Generated<string>;
  max_attempts: Generated<number>;
  name: string;
  secret_encrypted: string;
  site_id: string | null;
  updated_at: Generated<Timestamp>;
  url: string;
  version: Generated<number>;
}

export interface DB {
  admin_invitations: AdminInvitations;
  admin_role_permissions: AdminRolePermissions;
  admin_roles: AdminRoles;
  admin_sessions: AdminSessions;
  admin_user_roles: AdminUserRoles;
  admin_users: AdminUsers;
  api_tokens: ApiTokens;
  app_login_codes: AppLoginCodes;
  app_oauth_accounts: AppOauthAccounts;
  app_password_resets: AppPasswordResets;
  app_refresh_tokens: AppRefreshTokens;
  app_role_permissions: AppRolePermissions;
  app_roles: AppRoles;
  app_user_roles: AppUserRoles;
  app_users: AppUsers;
  assist_runs: AssistRuns;
  audit_events: AuditEvents;
  change_set_items: ChangeSetItems;
  change_sets: ChangeSets;
  content_health_findings: ContentHealthFindings;
  content_revisions: ContentRevisions;
  deployment_connections: DeploymentConnections;
  deployment_runs: DeploymentRuns;
  editor_presence: EditorPresence;
  email_confirmations: EmailConfirmations;
  entries: Entries;
  entry_heads: EntryHeads;
  extension_hook_runs: ExtensionHookRuns;
  field_reads: FieldReads;
  jobs: Jobs;
  locales: Locales;
  media_assets: MediaAssets;
  media_folders: MediaFolders;
  media_references: MediaReferences;
  media_upload_grants: MediaUploadGrants;
  media_variants: MediaVariants;
  model_active_versions: ModelActiveVersions;
  models: Models;
  outbox_events: OutboxEvents;
  password_resets: PasswordResets;
  preview_tokens: PreviewTokens;
  publication_log: PublicationLog;
  publication_snapshots: PublicationSnapshots;
  publication_state: PublicationState;
  relation_edges: RelationEdges;
  scheduled_publications: ScheduledPublications;
  schema_change_jobs: SchemaChangeJobs;
  schema_drafts: SchemaDrafts;
  schema_revisions: SchemaRevisions;
  schema_settings: SchemaSettings;
  setup_tokens: SetupTokens;
  site_app_roles: SiteAppRoles;
  sites: Sites;
  system_settings: SystemSettings;
  system_versions: SystemVersions;
  token_reads: TokenReads;
  unique_values: UniqueValues;
  webhook_deliveries: WebhookDeliveries;
  webhooks: Webhooks;
}
