/** Every admin route the client calls (packages B, D, F and G, `apps/api/src/routes/admin/**`). */
export const ADMIN_PATHS = {
  setup: '/api/admin/setup',
  csrf: '/api/admin/auth/csrf',
  login: '/api/admin/auth/login',
  logout: '/api/admin/auth/logout',
  me: '/api/admin/auth/me',
  password: '/api/admin/auth/me/password',
  sessions: '/api/admin/auth/sessions',
  passwordReset: '/api/admin/auth/password-reset',
  passwordResetConfirm: '/api/admin/auth/password-reset/confirm',
  users: '/api/admin/users',
  invitations: '/api/admin/invitations',
  inspectInvitation: '/api/admin/invitations/inspect',
  acceptInvitation: '/api/admin/invitations/accept',
  roles: '/api/admin/roles',
  tokens: '/api/admin/tokens',
  audit: '/api/admin/audit',
  models: '/api/admin/models',
  components: '/api/admin/components',
  schema: '/api/admin/schema',
  schemaChanges: '/api/admin/schema/changes',
  schemaSettings: '/api/admin/schema/settings',
  locales: '/api/admin/locales',
  mediaFolders: '/api/admin/media/folders',
  mediaAssets: '/api/admin/media/assets',
  mediaUploads: '/api/admin/media/uploads',
  appUsers: '/api/admin/app-users',
  appRoles: '/api/admin/app-roles',
  content: '/api/admin/content',
  contentCounts: '/api/admin/content-counts',
  contentHealth: '/api/admin/content-health',
  presence: '/api/admin/presence',
  editorManifest: '/api/admin/extensions/editors',
  jobs: '/api/admin/jobs',
  schedules: '/api/admin/publishing/schedules',
  changeSets: '/api/admin/change-sets',
  snapshots: '/api/admin/snapshots',
  webhooks: '/api/admin/webhooks',
  deploymentConnections: '/api/admin/deployments/connections',
  deploymentRuns: '/api/admin/deployments/runs',
  preview: '/api/admin/preview',
  previewTokens: '/api/admin/preview/tokens',
} as const;

export const withId = (base: string, id: string) => `${base}/${encodeURIComponent(id)}`;
