import { randomUUID } from 'node:crypto';
import { AppError } from '../helpers/appError.js';
import { generateToken } from '../helpers/tokens.js';
import type { PermissionEvaluator } from '../permissions/types.js';
import { assertDestinationAllowed } from '../publishing/destination.js';
import { decodeCursor, pageSize, toPage, type Page } from '../publishing/pagination.js';
import { adminIdOf } from '../publishing/principals.js';
import type { PublishingRuntime } from '../publishing/runtime.js';
import * as webhooksRepository from '../repositories/webhooks.js';
import type { WebhookDeliveryRow, WebhookSummaryRow } from '../repositories/webhooks.js';
import { isValidEventPattern, WEBHOOK_EVENT_CATALOGUE, WEBHOOK_TEST_EVENT } from '../webhooks/catalogue.js';
import { enqueueDelivery, type WebhookBody } from '../webhooks/enqueue.js';
import type { SiteActorContext, SiteRef } from './actorContext.js';
import { recordAudit } from './audit.js';
import { canPerformOnEverySite } from './networkScope.js';

/**
 * Webhooks (package H): signed POSTs for outbox events. The signing secret is generated by Shapio, shown
 * once (on creation and rotation), stored encrypted, and never returned again.
 *
 * Sites (plan §H): a webhook belongs to one site (that site's events) or to the network (`site` null: every
 * site's events, and network events). A site sees its own and the network webhooks; changing a network
 * webhook needs `webhooks.manage` on every site.
 */
export type WebhookContext = SiteActorContext & { permissions: PermissionEvaluator };
export type DeliveryStatus = 'pending' | 'retrying' | 'succeeded' | 'dead';

export type WebhookView = {
  id: string;
  /** The webhook's site; null for a network webhook (every site's events). */
  site: SiteRef | null;
  name: string;
  url: string;
  events: string[];
  enabled: boolean;
  allowPrivateNetwork: boolean;
  maxAttempts: number;
  lastDelivery: { status: DeliveryStatus; at: Date } | null;
  createdBy: string | null;
  createdAt: Date;
  updatedAt: Date;
  version: number;
};

export type WebhookDeliveryView = {
  id: string;
  webhookId: string;
  eventId: string | null;
  eventType: string;
  isTest: boolean;
  status: DeliveryStatus;
  attempts: number;
  lastResponseStatus: number | null;
  lastError: string | null;
  payload: unknown;
  attemptLog: unknown[];
  createdAt: Date;
  updatedAt: Date;
  deliveredAt: Date | null;
};

const SECRET_PREFIX = 'whsec_';

const toView = (row: WebhookSummaryRow): WebhookView => ({
  id: row.id,
  site: row.site_id && row.site_key ? { id: row.site_id, key: row.site_key } : null,
  name: row.name,
  url: row.url,
  events: row.events,
  enabled: row.enabled,
  allowPrivateNetwork: row.allow_private_network,
  maxAttempts: row.max_attempts,
  lastDelivery:
    row.last_status && row.last_at ? { status: row.last_status as DeliveryStatus, at: row.last_at } : null,
  createdBy: row.created_by,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  version: row.version,
});

export const toDeliveryView = (row: WebhookDeliveryRow): WebhookDeliveryView => ({
  id: row.id,
  webhookId: row.webhook_id,
  eventId: row.event_id,
  eventType: row.event_type,
  isTest: row.is_test,
  status: row.status as DeliveryStatus,
  attempts: row.attempts,
  lastResponseStatus: row.last_response_status,
  lastError: row.last_error,
  payload: row.payload,
  attemptLog: Array.isArray(row.attempt_log) ? row.attempt_log : [],
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  deliveredAt: row.delivered_at,
});

const webhookNotFound = (id: string) => new AppError(404, 'WEBHOOK_NOT_FOUND', `No webhook ${id}`, { id });

const assertEvents = (events: readonly string[]) => {
  const invalid = events.filter((event) => !isValidEventPattern(event));
  if (invalid.length > 0) {
    throw new AppError(400, 'INVALID_EVENTS', `Unknown events: ${invalid.join(', ')}`, { invalid });
  }
};

export const listEventTypes = () => WEBHOOK_EVENT_CATALOGUE;

export const listWebhooks = async (runtime: PublishingRuntime, site: SiteRef) =>
  (await webhooksRepository.list(site.id, runtime.db)).map(toView);

export const getWebhook = async (
  runtime: PublishingRuntime,
  site: SiteRef,
  id: string,
): Promise<WebhookView> => {
  const row = await webhooksRepository.findSummaryVisible(site.id, id, runtime.db);
  if (!row) {
    throw webhookNotFound(id);
  }
  return toView(row);
};

const networkForbidden = () =>
  new AppError(403, 'FORBIDDEN', 'Network webhooks need webhooks.manage on every site');

const assertNetworkManager = async (context: WebhookContext) => {
  if (!(await canPerformOnEverySite(context.permissions, context.actor, 'webhooks.manage'))) {
    throw networkForbidden();
  }
};

/**
 * The webhook (with its secret) the caller may change: one of the site's, or a network one when the caller
 * manages webhooks on every site. Another site's webhook is not found.
 */
const findChangeable = async (runtime: PublishingRuntime, context: WebhookContext, id: string) => {
  const row = await webhooksRepository.findVisible(context.site.id, id, runtime.db);
  if (!row) {
    throw webhookNotFound(id);
  }
  if (row.site_id === null) {
    await assertNetworkManager(context);
  }
  return row;
};

export type WebhookInput = {
  /** A network webhook (every site's events) instead of one of the request's site. */
  network?: boolean;
  name: string;
  url: string;
  events: string[];
  enabled?: boolean;
  allowPrivateNetwork?: boolean;
  maxAttempts?: number;
};

export const createWebhook = async (
  runtime: PublishingRuntime,
  context: WebhookContext,
  input: WebhookInput,
): Promise<{ webhook: WebhookView; secret: string }> => {
  assertEvents(input.events);
  if (input.network) {
    await assertNetworkManager(context);
  }
  await assertDestinationAllowed(runtime, input.url, input.allowPrivateNetwork ?? false);
  const secret = `${SECRET_PREFIX}${generateToken()}`;
  const id = await runtime.db.transaction().execute(async (trx) => {
    const created = await webhooksRepository.insert(
      {
        site_id: input.network ? null : context.site.id,
        name: input.name.trim(),
        url: input.url,
        events: [...new Set(input.events)],
        enabled: input.enabled ?? true,
        allow_private_network: input.allowPrivateNetwork ?? false,
        ...(input.maxAttempts !== undefined ? { max_attempts: input.maxAttempts } : {}),
        secret_encrypted: runtime.secrets.encrypt(secret),
        created_by: adminIdOf(context.actor),
      },
      trx,
    );
    await recordAudit(trx, {
      ...context,
      action: 'webhook.create',
      target: { type: 'webhook', id: created.id },
      metadata: { name: input.name, url: input.url, events: input.events, network: input.network ?? false },
    });
    return created.id;
  });
  return { webhook: await getWebhook(runtime, context.site, id), secret };
};

const versionConflict = () =>
  new AppError(409, 'VERSION_CONFLICT', 'The webhook changed since you loaded it. Reload and try again.');

export const updateWebhook = async (
  runtime: PublishingRuntime,
  context: WebhookContext,
  id: string,
  input: Partial<Omit<WebhookInput, 'network'>> & { expectedVersion: number },
): Promise<WebhookView> => {
  const current = await findChangeable(runtime, context, id);
  if (input.events) {
    assertEvents(input.events);
  }
  if (input.url !== undefined || input.allowPrivateNetwork !== undefined) {
    await assertDestinationAllowed(
      runtime,
      input.url ?? current.url,
      input.allowPrivateNetwork ?? current.allow_private_network,
    );
  }
  await runtime.db.transaction().execute(async (trx) => {
    const updated = await webhooksRepository.update(
      id,
      {
        ...(input.name !== undefined ? { name: input.name.trim() } : {}),
        ...(input.url !== undefined ? { url: input.url } : {}),
        ...(input.events !== undefined ? { events: [...new Set(input.events)] } : {}),
        ...(input.enabled !== undefined ? { enabled: input.enabled } : {}),
        ...(input.allowPrivateNetwork !== undefined
          ? { allow_private_network: input.allowPrivateNetwork }
          : {}),
        ...(input.maxAttempts !== undefined ? { max_attempts: input.maxAttempts } : {}),
      },
      input.expectedVersion,
      new Date(),
      trx,
    );
    if (!updated) {
      throw versionConflict();
    }
    const { expectedVersion: _version, ...changes } = input;
    await recordAudit(trx, {
      ...context,
      action: 'webhook.update',
      target: { type: 'webhook', id },
      metadata: { changes: Object.keys(changes) },
    });
  });
  return getWebhook(runtime, context.site, id);
};

export const deleteWebhook = async (runtime: PublishingRuntime, context: WebhookContext, id: string) => {
  await findChangeable(runtime, context, id);
  await runtime.db.transaction().execute(async (trx) => {
    const removed = await webhooksRepository.deleteById(id, trx);
    if (removed.numDeletedRows === 0n) {
      throw webhookNotFound(id);
    }
    await recordAudit(trx, { ...context, action: 'webhook.delete', target: { type: 'webhook', id } });
  });
};

export const rotateWebhookSecret = async (
  runtime: PublishingRuntime,
  context: WebhookContext,
  id: string,
): Promise<{ webhook: WebhookView; secret: string }> => {
  await findChangeable(runtime, context, id);
  const secret = `${SECRET_PREFIX}${generateToken()}`;
  await runtime.db.transaction().execute(async (trx) => {
    const updated = await webhooksRepository.update(
      id,
      { secret_encrypted: runtime.secrets.encrypt(secret) },
      undefined,
      new Date(),
      trx,
    );
    if (!updated) {
      throw webhookNotFound(id);
    }
    await recordAudit(trx, { ...context, action: 'webhook.rotate_secret', target: { type: 'webhook', id } });
  });
  return { webhook: await getWebhook(runtime, context.site, id), secret };
};

/** Queues a `webhook.test` delivery (also for disabled webhooks, so they can be checked before enabling). */
export const sendTestDelivery = async (
  runtime: PublishingRuntime,
  context: WebhookContext,
  id: string,
): Promise<WebhookDeliveryView> => {
  const webhook = await findChangeable(runtime, context, id);
  const body: WebhookBody = {
    id: randomUUID(),
    type: WEBHOOK_TEST_EVENT,
    createdAt: runtime.now().toISOString(),
    site: webhook.site_id === null ? null : context.site,
    data: { webhookId: id, message: 'A test delivery from Shapio' },
  };
  const delivery = await runtime.db.transaction().execute(async (trx) => {
    const queued = await enqueueDelivery(trx, { webhook, eventId: null, body, isTest: true });
    await recordAudit(trx, { ...context, action: 'webhook.test', target: { type: 'webhook', id } });
    return queued;
  });
  if (!delivery) {
    throw new Error('Test delivery was not created');
  }
  return toDeliveryView(delivery);
};

export const listDeliveries = async (
  runtime: PublishingRuntime,
  site: SiteRef,
  webhookId: string,
  query: { cursor?: string; limit?: number },
): Promise<Page<WebhookDeliveryView>> => {
  if (!(await webhooksRepository.findSummaryVisible(site.id, webhookId, runtime.db))) {
    throw webhookNotFound(webhookId);
  }
  const limit = pageSize(query.limit);
  const rows = await webhooksRepository.listDeliveries(
    webhookId,
    decodeCursor(query.cursor),
    limit + 1,
    runtime.db,
  );
  return toPage(rows, limit, toDeliveryView);
};

/** Sends a delivery's payload again, as a new delivery (the original's log stays as it was). */
export const redeliver = async (
  runtime: PublishingRuntime,
  context: WebhookContext,
  webhookId: string,
  deliveryId: string,
): Promise<WebhookDeliveryView> => {
  const webhook = await findChangeable(runtime, context, webhookId);
  const original = await webhooksRepository.findDelivery(deliveryId, runtime.db);
  if (!original || original.webhook_id !== webhookId) {
    throw new AppError(404, 'DELIVERY_NOT_FOUND', `No delivery ${deliveryId}`);
  }
  const delivery = await runtime.db.transaction().execute(async (trx) => {
    const queued = await enqueueDelivery(trx, {
      webhook,
      eventId: null,
      body: original.payload as WebhookBody,
      isTest: original.is_test,
    });
    await recordAudit(trx, {
      ...context,
      action: 'webhook.redeliver',
      target: { type: 'webhook', id: webhookId },
      metadata: { deliveryId },
    });
    return queued;
  });
  if (!delivery) {
    throw new Error('Redelivery was not created');
  }
  return toDeliveryView(delivery);
};
