// Embeds documentation/delivery-api.md into src/generated/deliveryApiDoc.ts, served as the
// `shapio://docs/delivery-api` resource. Run before building; a unit test fails when the copy is stale.
import { readFile, writeFile } from 'node:fs/promises';

const source = new URL('../../../documentation/delivery-api.md', import.meta.url);
const target = new URL('../src/generated/deliveryApiDoc.ts', import.meta.url);

const text = await readFile(source, 'utf8');
await writeFile(
  target,
  `// Generated by scripts/embedDocs.mjs from documentation/delivery-api.md. Do not edit.\nexport const DELIVERY_API_DOC = ${JSON.stringify(text)};\n`,
);
