import {
  isModelDefinition,
  routeKeyOf,
  toTypeName,
  type FieldDefinition,
  type SchemaDefinition,
} from '@shapio/schema';
import type { SchemaSnapshot } from '../snapshot.js';

/**
 * TypeScript declarations for the active schema (`shapio types generate`). Derived in memory from the
 * registry like OpenAPI, never committed into Shapio itself: the project that consumes the API writes them
 * to its own source tree. Output types describe delivery responses; `<Name>Input` types describe writes.
 */
type Mode = 'output' | 'input';

const PRELUDE = `// Generated by \`shapio types generate\`. Do not edit: regenerate after changing models.

export type RichTextNode = {
  type: string;
  attrs?: Record<string, unknown>;
  content?: RichTextNode[];
  text?: string;
  marks?: Array<{ type: string; attrs?: Record<string, unknown> }>;
};

export type RichText = { format: 'shapio-richtext'; version: 1; doc: RichTextNode };

/**
 * Rich text as delivery returns it, per the request's \`richText\`: \`doc\` with \`json\` (the default), sanitized
 * \`html\` rendered from the document with \`html\`, both with \`both\`.
 */
export type RichTextOutput = { format: 'shapio-richtext'; version: 1; doc?: RichTextNode; html?: string };

export type MediaAsset = {
  id: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  width: number | null;
  height: number | null;
  alt: string;
  caption: string;
  focalPoint: { x: number; y: number } | null;
  /** Stable for public assets; signed and expiring for private ones. */
  url: string;
  urlExpiresAt: string | null;
  variants: Array<{ name: string; width: number | null; height: number | null; format: string; mimeType: string; url: string }>;
};

/** A relation value: the target entry's ID, or the entry itself when populated. */
export type Related<T> = string | T;

export type EntrySystemFields = {
  id: string;
  locale: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};
`;

const quote = (text: string) => JSON.stringify(text);
const comment = (text: string | undefined) => (text ? `  /** ${text.replace(/\*\//g, '*\\/')} */\n` : '');

/** A field's one-line doc comment: its help text or label, plus a code field's language. */
const fieldComment = (field: FieldDefinition) => {
  const text = field.description ?? field.label;
  return comment(field.type === 'code' ? `${text} (Code: ${field.settings.language})` : text);
};

const scalarType = (field: FieldDefinition): string => {
  switch (field.type) {
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enum': {
      const union = field.settings.values.map((entry) => quote(entry.value)).join(' | ');
      return field.settings.multiple ? `Array<${union}>` : union;
    }
    case 'json':
      return 'unknown';
    default:
      // Strings, including code, decimal/biginteger (exact) and canonical ISO date/time text.
      return 'string';
  }
};

const many = (isList: boolean, type: string) => (isList ? `Array<${type}>` : type);

const fieldType = (field: FieldDefinition, snapshot: SchemaSnapshot, mode: Mode): string => {
  const nameOf = (id: string) => {
    const definition = snapshot.byId.get(id)?.definition;
    return definition ? `${toTypeName(definition.apiKey)}${mode === 'input' ? 'Input' : ''}` : 'unknown';
  };
  switch (field.type) {
    case 'richtext':
      return mode === 'output' ? 'RichTextOutput' : 'RichText';
    case 'media':
      return many(field.settings.multiple, mode === 'output' ? 'MediaAsset' : 'string');
    case 'relation': {
      const target = snapshot.byId.get(field.settings.target)?.definition;
      const item = mode === 'output' && target ? `Related<${toTypeName(target.apiKey)}>` : 'string';
      return many(field.settings.cardinality === 'many', item);
    }
    case 'component':
      return many(field.settings.repeatable, nameOf(field.settings.component));
    case 'dynamiczone': {
      const members = field.settings.components.map((id) => {
        const component = snapshot.byId.get(id)?.definition;
        return component ? `({ __component: ${quote(component.apiKey)} } & ${nameOf(id)})` : 'never';
      });
      return `Array<${members.join(' | ') || 'never'}>`;
    }
    default:
      return scalarType(field);
  }
};

const declaration = (definition: SchemaDefinition, snapshot: SchemaSnapshot, mode: Mode): string => {
  const name = `${toTypeName(definition.apiKey)}${mode === 'input' ? 'Input' : ''}`;
  const lines = definition.fields
    .filter((field) => !field.deprecated)
    .map((field) => {
      const type = fieldType(field, snapshot, mode);
      // Output: every field is present (null when empty). Input: send only what changes; null clears.
      return mode === 'output'
        ? `${fieldComment(field)}  ${field.apiKey}: ${type} | null;`
        : `${fieldComment(field)}  ${field.apiKey}?: ${type} | null;`;
    });
  const base = mode === 'output' && isModelDefinition(definition) ? 'EntrySystemFields & ' : '';
  const ids =
    definition.kind === 'collection'
      ? `${definition.kind} \`${definition.apiKey}\`, delivery route \`${routeKeyOf(definition)}\``
      : `${definition.kind} \`${definition.apiKey}\``;
  return `/** ${definition.label} (${ids}) */\nexport type ${name} = ${base}{\n${lines.join('\n')}\n};\n`;
};

/**
 * The declarations for every model and component of a snapshot, plus two maps keyed by API ID: the entry
 * type (`ShapioModels`) and the delivery route key (`ShapioRouteKeys`, `{ article: 'articles' }`).
 */
export const generateTypeScript = (snapshot: SchemaSnapshot): string => {
  const definitions = [...snapshot.definitions]
    .map((active) => active.definition)
    .sort((a, b) => a.apiKey.localeCompare(b.apiKey));
  const body = definitions.flatMap((definition) => [
    declaration(definition, snapshot, 'output'),
    declaration(definition, snapshot, 'input'),
  ]);
  const models = definitions.filter(isModelDefinition);
  const map = `/** Delivery entry type by model API ID. */\nexport type ShapioModels = {\n${models
    .map((model) => `  ${model.apiKey}: ${toTypeName(model.apiKey)};`)
    .join('\n')}\n};\n`;
  const routeKeys = `/** Delivery route key (\`/api/content/:routeKey\`) by model API ID. */\nexport type ShapioRouteKeys = {\n${models
    .map((model) => `  ${model.apiKey}: '${routeKeyOf(model)}';`)
    .join('\n')}\n};\n`;
  return `${PRELUDE}\n// Schema version ${snapshot.version}\n\n${body.join('\n')}\n${map}\n${routeKeys}`;
};
