/**
 * What the MySQL layer needs to know about Shapio's tables (ADR 0001, "MySQL"): primary keys, the columns
 * PostgreSQL fills by default that MySQL cannot (UUIDs are generated here, so an emulated `RETURNING` knows
 * the key; the change sequence has no column default), identity columns, unique keys by the columns a
 * conflict target names, and which columns may be NULL (for `ORDER BY` null placement).
 *
 * Generated from the migrated PostgreSQL catalog together with the MySQL baseline;
 * `test/mysqlBaseline.int.test.ts` checks it against the migrated MySQL schema.
 */
export type GeneratedValue = 'uuid' | 'entry_heads_change_seq';

export type UniqueKey = { name: string; columns: readonly string[] };

export type MysqlTableInfo = {
  primaryKey: readonly string[];
  /** An AUTO_INCREMENT column (PostgreSQL identity). */
  identity?: string;
  generated?: Readonly<Record<string, GeneratedValue>>;
  columns: readonly string[];
  nullable: readonly string[];
  /** `DATETIME(6)` columns (PostgreSQL timestamptz): text bound to them is normalised to UTC DATETIME text. */
  timestamps?: readonly string[];
  uniqueKeys: readonly UniqueKey[];
};

export const MYSQL_TABLES: Readonly<Record<string, MysqlTableInfo>> = {
  admin_invitations: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'email',
      'token_hash',
      'invited_by',
      'expires_at',
      'accepted_at',
      'revoked_at',
      'created_at',
      'updated_at',
      'role_assignments',
    ],
    nullable: ['token_hash', 'invited_by', 'accepted_at', 'revoked_at'],
    timestamps: ['expires_at', 'accepted_at', 'revoked_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_invitations_pkey', columns: ['id'] },
      { name: 'admin_invitations_token_hash_key', columns: ['token_hash'] },
    ],
  },
  admin_role_permissions: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'role_id', 'action', 'model_id', 'condition', 'field_ids', 'created_at', 'updated_at'],
    nullable: ['model_id', 'condition', 'field_ids'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_role_permissions_grant_uq', columns: ['role_id', 'action', 'model_id'] },
      { name: 'admin_role_permissions_pkey', columns: ['id'] },
    ],
  },
  admin_roles: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'key', 'name', 'description', 'kind', 'is_system', 'version', 'created_at', 'updated_at'],
    nullable: [],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_roles_key_key', columns: ['key'] },
      { name: 'admin_roles_pkey', columns: ['id'] },
    ],
  },
  admin_sessions: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'admin_user_id',
      'token_hash',
      'csrf_secret',
      'ip',
      'user_agent',
      'last_seen_at',
      'expires_at',
      'revoked_at',
      'rotation_required',
      'created_at',
      'updated_at',
    ],
    nullable: ['ip', 'user_agent', 'revoked_at'],
    timestamps: ['last_seen_at', 'expires_at', 'revoked_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_sessions_pkey', columns: ['id'] },
      { name: 'admin_sessions_token_hash_key', columns: ['token_hash'] },
    ],
  },
  admin_user_roles: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['admin_user_id', 'role_id', 'created_at', 'updated_at', 'site_id', 'id'],
    nullable: ['site_id'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_user_roles_assignment_uq', columns: ['admin_user_id', 'role_id', 'site_id'] },
      { name: 'admin_user_roles_pk', columns: ['id'] },
    ],
  },
  admin_users: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'email',
      'name',
      'password_hash',
      'status',
      'last_login_at',
      'password_changed_at',
      'created_at',
      'updated_at',
    ],
    nullable: ['last_login_at'],
    timestamps: ['last_login_at', 'password_changed_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'admin_users_email_key', columns: ['email'] },
      { name: 'admin_users_pkey', columns: ['id'] },
    ],
  },
  api_tokens: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'name',
      'token_hash',
      'token_prefix',
      'role_id',
      'created_by',
      'expires_at',
      'last_used_at',
      'revoked_at',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['created_by', 'expires_at', 'last_used_at', 'revoked_at', 'site_id'],
    timestamps: ['expires_at', 'last_used_at', 'revoked_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'api_tokens_pkey', columns: ['id'] },
      { name: 'api_tokens_token_hash_key', columns: ['token_hash'] },
    ],
  },
  app_login_codes: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'app_user_id', 'code_hash', 'expires_at', 'used_at', 'created_at', 'code_challenge'],
    nullable: ['used_at'],
    timestamps: ['expires_at', 'used_at', 'created_at'],
    uniqueKeys: [
      { name: 'app_login_codes_code_hash_key', columns: ['code_hash'] },
      { name: 'app_login_codes_pkey', columns: ['id'] },
    ],
  },
  app_oauth_accounts: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'app_user_id',
      'provider',
      'provider_user_id',
      'email',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['email'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'app_oauth_accounts_identity_uq', columns: ['site_id', 'provider', 'provider_user_id'] },
      { name: 'app_oauth_accounts_pkey', columns: ['id'] },
    ],
  },
  app_password_resets: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'app_user_id',
      'email',
      'token_hash',
      'expires_at',
      'used_at',
      'created_at',
      'updated_at',
    ],
    nullable: ['token_hash', 'used_at'],
    timestamps: ['expires_at', 'used_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'app_password_resets_pkey', columns: ['id'] },
      { name: 'app_password_resets_token_hash_key', columns: ['token_hash'] },
    ],
  },
  app_refresh_tokens: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'app_user_id',
      'family_id',
      'token_hash',
      'expires_at',
      'used_at',
      'reuse_grace_used_at',
      'revoked_at',
      'revoked_reason',
      'ip',
      'user_agent',
      'created_at',
    ],
    nullable: ['used_at', 'reuse_grace_used_at', 'revoked_at', 'revoked_reason', 'ip', 'user_agent'],
    timestamps: ['expires_at', 'used_at', 'reuse_grace_used_at', 'revoked_at', 'created_at'],
    uniqueKeys: [
      { name: 'app_refresh_tokens_pkey', columns: ['id'] },
      { name: 'app_refresh_tokens_token_hash_key', columns: ['token_hash'] },
    ],
  },
  app_role_permissions: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'role_id', 'action', 'model_id', 'condition', 'field_ids', 'created_at', 'updated_at'],
    nullable: ['model_id', 'condition', 'field_ids'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'app_role_permissions_grant_uq', columns: ['role_id', 'action', 'model_id'] },
      { name: 'app_role_permissions_pkey', columns: ['id'] },
    ],
  },
  app_roles: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'key', 'name', 'description', 'is_system', 'version', 'created_at', 'updated_at'],
    nullable: [],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'app_roles_key_key', columns: ['key'] },
      { name: 'app_roles_pkey', columns: ['id'] },
    ],
  },
  app_user_roles: {
    primaryKey: ['app_user_id', 'role_id'],
    columns: ['app_user_id', 'role_id', 'created_at', 'site_id'],
    nullable: [],
    timestamps: ['created_at'],
    uniqueKeys: [{ name: 'app_user_roles_pk', columns: ['app_user_id', 'role_id'] }],
  },
  app_users: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'email',
      'name',
      'password_hash',
      'confirmed_at',
      'blocked_at',
      'last_login_at',
      'password_changed_at',
      'deleted_at',
      'created_at',
      'updated_at',
      'token_version',
      'site_id',
    ],
    nullable: [
      'password_hash',
      'confirmed_at',
      'blocked_at',
      'last_login_at',
      'password_changed_at',
      'deleted_at',
    ],
    timestamps: [
      'confirmed_at',
      'blocked_at',
      'last_login_at',
      'password_changed_at',
      'deleted_at',
      'created_at',
      'updated_at',
    ],
    uniqueKeys: [
      { name: 'app_users_email_uq', columns: ['site_id', 'email'] },
      { name: 'app_users_pkey', columns: ['id'] },
    ],
  },
  assist_runs: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'site_id',
      'actor_type',
      'actor_id',
      'action',
      'rule',
      'provider',
      'model',
      'input_tokens',
      'output_tokens',
      'duration_ms',
      'status',
      'error_code',
      'job_id',
      'created_at',
      'finished_at',
    ],
    nullable: ['rule', 'error_code', 'job_id', 'finished_at'],
    timestamps: ['created_at', 'finished_at'],
    uniqueKeys: [{ name: 'assist_runs_pkey', columns: ['id'] }],
  },
  audit_events: {
    primaryKey: ['id'],
    identity: 'seq',
    generated: { id: 'uuid' },
    columns: [
      'id',
      'occurred_at',
      'actor_type',
      'actor_id',
      'action',
      'target_type',
      'target_id',
      'outcome',
      'request_id',
      'ip',
      'metadata',
      'site_id',
      'seq',
    ],
    nullable: ['actor_id', 'target_type', 'target_id', 'request_id', 'ip', 'site_id'],
    timestamps: ['occurred_at'],
    uniqueKeys: [
      { name: 'audit_events_pkey', columns: ['id'] },
      { name: 'audit_events_seq_key', columns: ['seq'] },
    ],
  },
  change_set_items: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'change_set_id',
      'kind',
      'position',
      'entry_id',
      'model_id',
      'locale',
      'action',
      'source_revision_id',
      'schema_draft_id',
      'status',
      'error',
      'ship_state',
      'created_at',
      'site_id',
    ],
    nullable: [
      'entry_id',
      'model_id',
      'locale',
      'action',
      'source_revision_id',
      'schema_draft_id',
      'error',
      'ship_state',
    ],
    timestamps: ['created_at'],
    uniqueKeys: [
      { name: 'change_set_items_draft_uq', columns: ['schema_draft_id'] },
      { name: 'change_set_items_entry_uq', columns: ['change_set_id', 'entry_id', 'locale'] },
      { name: 'change_set_items_pkey', columns: ['id'] },
    ],
  },
  change_sets: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'title',
      'description',
      'status',
      'ship_phase',
      'source',
      'restore_of_seq',
      'scheduled_for',
      'schedule_job_id',
      'scheduled_by',
      'scheduled_by_token',
      'ship_job_id',
      'ship_mode',
      'ship_requested_by',
      'ship_requested_by_token',
      'acknowledge_breaking',
      'acknowledge_destructive',
      'deployment_connection_id',
      'deployment_run_id',
      'shipped_at',
      'shipped_seq',
      'schema_version_after',
      'error',
      'restore_report',
      'created_by',
      'created_by_token',
      'version',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: [
      'ship_phase',
      'restore_of_seq',
      'scheduled_for',
      'schedule_job_id',
      'scheduled_by',
      'scheduled_by_token',
      'ship_job_id',
      'ship_mode',
      'ship_requested_by',
      'ship_requested_by_token',
      'deployment_connection_id',
      'deployment_run_id',
      'shipped_at',
      'shipped_seq',
      'schema_version_after',
      'error',
      'created_by',
      'created_by_token',
    ],
    timestamps: ['scheduled_for', 'shipped_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'change_sets_id_site_uq', columns: ['id', 'site_id'] },
      { name: 'change_sets_pkey', columns: ['id'] },
    ],
  },
  content_health_findings: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'entry_id',
      'model_id',
      'locale',
      'rule',
      'subject',
      'severity',
      'path',
      'details',
      'first_seen_at',
      'last_seen_at',
      'resolved_at',
      'site_id',
    ],
    nullable: ['path', 'resolved_at'],
    timestamps: ['first_seen_at', 'last_seen_at', 'resolved_at'],
    uniqueKeys: [
      {
        name: 'content_health_findings_entry_id_locale_rule_subject_key',
        columns: ['entry_id', 'locale', 'rule', 'subject'],
      },
      { name: 'content_health_findings_pkey', columns: ['id'] },
    ],
  },
  content_revisions: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'entry_id',
      'locale',
      'schema_revision_id',
      'data',
      'reason',
      'author_type',
      'author_id',
      'parent_revision_id',
      'created_at',
    ],
    nullable: ['author_id', 'parent_revision_id'],
    timestamps: ['created_at'],
    uniqueKeys: [{ name: 'content_revisions_pkey', columns: ['id'] }],
  },
  deployment_connections: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'name',
      'provider',
      'settings',
      'secrets_encrypted',
      'secret_env_refs',
      'delivery_role_id',
      'preview_url_template',
      'trigger_policy',
      'debounce_seconds',
      'allow_private_network',
      'enabled',
      'version',
      'created_by',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['delivery_role_id', 'preview_url_template', 'created_by'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [{ name: 'deployment_connections_pkey', columns: ['id'] }],
  },
  deployment_runs: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'connection_id',
      'status',
      'status_rank',
      'trigger',
      'snapshot_seq',
      'schema_version',
      'retry_of',
      'provider_ref',
      'log_url',
      'site_url',
      'error',
      'timeline',
      'job_id',
      'triggered_at',
      'finished_at',
      'created_by',
      'created_at',
      'updated_at',
      'change_set_id',
    ],
    nullable: [
      'snapshot_seq',
      'schema_version',
      'retry_of',
      'provider_ref',
      'log_url',
      'site_url',
      'error',
      'job_id',
      'triggered_at',
      'finished_at',
      'created_by',
      'change_set_id',
    ],
    timestamps: ['triggered_at', 'finished_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'deployment_runs_pkey', columns: ['id'] },
      { name: 'deployment_runs_queued_uq', columns: ['connection_id'] },
    ],
  },
  editor_presence: {
    primaryKey: ['entry_id', 'admin_user_id', 'tab_id'],
    columns: ['entry_id', 'model_id', 'admin_user_id', 'tab_id', 'locale', 'started_at', 'last_seen_at'],
    nullable: ['locale'],
    timestamps: ['started_at', 'last_seen_at'],
    uniqueKeys: [{ name: 'editor_presence_pkey', columns: ['entry_id', 'admin_user_id', 'tab_id'] }],
  },
  email_confirmations: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'app_user_id',
      'email',
      'token_hash',
      'expires_at',
      'used_at',
      'created_at',
      'updated_at',
    ],
    nullable: ['token_hash', 'used_at'],
    timestamps: ['expires_at', 'used_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'email_confirmations_pkey', columns: ['id'] },
      { name: 'email_confirmations_token_hash_key', columns: ['token_hash'] },
    ],
  },
  entries: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'model_id',
      'owner_app_user_id',
      'created_by_admin_id',
      'created_at',
      'updated_at',
      'deleted_at',
      'site_id',
    ],
    nullable: ['owner_app_user_id', 'created_by_admin_id', 'deleted_at'],
    timestamps: ['created_at', 'updated_at', 'deleted_at'],
    uniqueKeys: [
      { name: 'entries_id_site_uq', columns: ['id', 'site_id'] },
      { name: 'entries_pkey', columns: ['id'] },
    ],
  },
  entry_heads: {
    primaryKey: ['entry_id', 'locale', 'state'],
    generated: { change_seq: 'entry_heads_change_seq' },
    columns: [
      'entry_id',
      'model_id',
      'locale',
      'state',
      'revision_id',
      'data',
      'autosaved_at',
      'version',
      'change_seq',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['autosaved_at'],
    timestamps: ['autosaved_at', 'created_at', 'updated_at'],
    uniqueKeys: [{ name: 'entry_heads_pkey', columns: ['entry_id', 'locale', 'state'] }],
  },
  extension_hook_runs: {
    primaryKey: ['event_id', 'hook'],
    columns: ['event_id', 'hook', 'job_id', 'completed_at'],
    nullable: ['job_id'],
    timestamps: ['completed_at'],
    uniqueKeys: [{ name: 'extension_hook_runs_pkey', columns: ['event_id', 'hook'] }],
  },
  field_reads: {
    primaryKey: ['day', 'site_id', 'model_id', 'field_path', 'principal_key', 'selection'],
    columns: [
      'day',
      'model_id',
      'field_path',
      'principal_key',
      'selection',
      'reads',
      'last_read_at',
      'site_id',
    ],
    nullable: [],
    timestamps: ['last_read_at'],
    uniqueKeys: [
      {
        name: 'field_reads_pkey',
        columns: ['day', 'site_id', 'model_id', 'field_path', 'principal_key', 'selection'],
      },
    ],
  },
  jobs: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'type',
      'payload',
      'status',
      'priority',
      'run_at',
      'attempts',
      'max_attempts',
      'idempotency_key',
      'locked_by',
      'locked_until',
      'checkpoint',
      'result',
      'last_error',
      'created_at',
      'updated_at',
      'finished_at',
    ],
    nullable: [
      'idempotency_key',
      'locked_by',
      'locked_until',
      'checkpoint',
      'result',
      'last_error',
      'finished_at',
    ],
    timestamps: ['run_at', 'locked_until', 'created_at', 'updated_at', 'finished_at'],
    uniqueKeys: [
      { name: 'jobs_idempotency_key_uq', columns: ['idempotency_key'] },
      { name: 'jobs_pkey', columns: ['id'] },
    ],
  },
  locales: {
    primaryKey: ['code'],
    columns: ['code', 'label', 'is_default', 'fallbacks', 'created_at', 'updated_at'],
    nullable: [],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'locales_pkey', columns: ['code'] },
      { name: 'locales_single_default_uq', columns: ['is_default'] },
    ],
  },
  media_assets: {
    primaryKey: ['id'],
    columns: [
      'id',
      'folder_id',
      'storage_driver',
      'storage_key',
      'original_filename',
      'mime_type',
      'size_bytes',
      'width',
      'height',
      'checksum_sha256',
      'alt',
      'caption',
      'focal_x',
      'focal_y',
      'visibility',
      'status',
      'processing_error',
      'created_by',
      'version',
      'deleted_at',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: [
      'folder_id',
      'width',
      'height',
      'checksum_sha256',
      'focal_x',
      'focal_y',
      'processing_error',
      'created_by',
      'deleted_at',
    ],
    timestamps: ['deleted_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'media_assets_pkey', columns: ['id'] },
      { name: 'media_assets_storage_key_uq', columns: ['storage_key'] },
    ],
  },
  media_folders: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'parent_id', 'name', 'created_by', 'version', 'created_at', 'updated_at', 'site_id'],
    nullable: ['parent_id', 'created_by'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'media_folders_id_site_uq', columns: ['id', 'site_id'] },
      { name: 'media_folders_pkey', columns: ['id'] },
      { name: 'media_folders_sibling_name_uq', columns: ['site_id', 'parent_id', 'name'] },
    ],
  },
  media_references: {
    primaryKey: ['asset_id', 'entry_id', 'locale', 'state', 'field_id'],
    columns: ['asset_id', 'entry_id', 'model_id', 'field_id', 'locale', 'state', 'created_at'],
    nullable: [],
    timestamps: ['created_at'],
    uniqueKeys: [
      { name: 'media_references_pk', columns: ['asset_id', 'entry_id', 'locale', 'state', 'field_id'] },
    ],
  },
  media_upload_grants: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'asset_id',
      'kind',
      'storage_driver',
      'storage_key',
      'original_filename',
      'declared_mime_type',
      'max_size_bytes',
      'folder_id',
      'visibility',
      'created_by',
      'created_by_principal',
      'status',
      'expires_at',
      'consumed_at',
      'created_at',
      'site_id',
    ],
    nullable: ['folder_id', 'created_by', 'consumed_at'],
    timestamps: ['expires_at', 'consumed_at', 'created_at'],
    uniqueKeys: [
      { name: 'media_upload_grants_pkey', columns: ['id'] },
      { name: 'media_upload_grants_storage_key_key', columns: ['storage_key'] },
    ],
  },
  media_variants: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'asset_id',
      'name',
      'width',
      'height',
      'format',
      'mime_type',
      'storage_key',
      'size_bytes',
      'checksum_sha256',
      'status',
      'error',
      'created_at',
      'updated_at',
    ],
    nullable: ['width', 'height', 'storage_key', 'size_bytes', 'checksum_sha256', 'error'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'media_variants_asset_name_uq', columns: ['asset_id', 'name'] },
      { name: 'media_variants_pkey', columns: ['id'] },
      { name: 'media_variants_storage_key_uq', columns: ['storage_key'] },
    ],
  },
  model_active_versions: {
    primaryKey: ['model_id'],
    columns: ['model_id', 'revision_id', 'version', 'schema_version', 'activated_at'],
    nullable: [],
    timestamps: ['activated_at'],
    uniqueKeys: [{ name: 'model_active_versions_pkey', columns: ['model_id'] }],
  },
  models: {
    primaryKey: ['id'],
    columns: ['id', 'kind', 'api_key', 'created_at', 'updated_at', 'deleted_at', 'site_id'],
    nullable: ['deleted_at', 'site_id'],
    timestamps: ['created_at', 'updated_at', 'deleted_at'],
    uniqueKeys: [
      { name: 'models_api_key_uq', columns: ['site_id', 'api_key'] },
      { name: 'models_pkey', columns: ['id'] },
    ],
  },
  outbox_events: {
    primaryKey: ['id'],
    identity: 'id',
    generated: { event_id: 'uuid' },
    columns: [
      'id',
      'event_id',
      'type',
      'aggregate_type',
      'aggregate_id',
      'payload',
      'created_at',
      'dispatched_at',
      'dispatch_attempts',
      'last_dispatch_error',
      'site_id',
    ],
    nullable: ['dispatched_at', 'last_dispatch_error', 'site_id'],
    timestamps: ['created_at', 'dispatched_at'],
    uniqueKeys: [
      { name: 'outbox_events_event_id_key', columns: ['event_id'] },
      { name: 'outbox_events_pkey', columns: ['id'] },
    ],
  },
  password_resets: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'admin_user_id', 'token_hash', 'expires_at', 'used_at', 'created_at', 'updated_at'],
    nullable: ['token_hash', 'used_at'],
    timestamps: ['expires_at', 'used_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'password_resets_pkey', columns: ['id'] },
      { name: 'password_resets_token_hash_key', columns: ['token_hash'] },
    ],
  },
  preview_tokens: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'token_hash',
      'token_prefix',
      'model_id',
      'entry_id',
      'locale',
      'connection_id',
      'delivery_role_id',
      'created_by',
      'expires_at',
      'revoked_at',
      'last_used_at',
      'created_at',
      'site_id',
    ],
    nullable: ['locale', 'connection_id', 'delivery_role_id', 'revoked_at', 'last_used_at'],
    timestamps: ['expires_at', 'revoked_at', 'last_used_at', 'created_at'],
    uniqueKeys: [
      { name: 'preview_tokens_pkey', columns: ['id'] },
      { name: 'preview_tokens_token_hash_key', columns: ['token_hash'] },
    ],
  },
  publication_log: {
    primaryKey: ['id'],
    identity: 'id',
    columns: [
      'id',
      'entry_id',
      'model_id',
      'locale',
      'revision_id',
      'from_seq',
      'to_seq',
      'published_at',
      'site_id',
    ],
    nullable: ['to_seq'],
    timestamps: ['published_at'],
    uniqueKeys: [
      { name: 'publication_log_open_uq', columns: ['entry_id', 'locale'] },
      { name: 'publication_log_pkey', columns: ['id'] },
    ],
  },
  publication_snapshots: {
    primaryKey: ['site_id', 'seq'],
    columns: [
      'seq',
      'schema_version',
      'source',
      'change_set_id',
      'actor_type',
      'actor_id',
      'created_at',
      'site_id',
    ],
    nullable: ['schema_version', 'change_set_id', 'actor_type', 'actor_id'],
    timestamps: ['created_at'],
    uniqueKeys: [{ name: 'publication_snapshots_pkey', columns: ['site_id', 'seq'] }],
  },
  publication_state: {
    primaryKey: ['site_id'],
    columns: ['last_seq', 'site_id'],
    nullable: [],
    uniqueKeys: [{ name: 'publication_state_pkey', columns: ['site_id'] }],
  },
  relation_edges: {
    primaryKey: ['source_entry_id', 'locale', 'state', 'field_id', 'position'],
    columns: ['source_entry_id', 'locale', 'state', 'field_id', 'position', 'target_entry_id'],
    nullable: [],
    uniqueKeys: [
      {
        name: 'relation_edges_pkey',
        columns: ['source_entry_id', 'locale', 'state', 'field_id', 'position'],
      },
    ],
  },
  scheduled_publications: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'entry_id',
      'model_id',
      'locale',
      'action',
      'run_at',
      'status',
      'created_by_token',
      'job_id',
      'snapshot_seq',
      'error',
      'executed_at',
      'created_by',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['created_by_token', 'job_id', 'snapshot_seq', 'error', 'executed_at', 'created_by'],
    timestamps: ['run_at', 'executed_at', 'created_at', 'updated_at'],
    uniqueKeys: [{ name: 'scheduled_publications_pkey', columns: ['id'] }],
  },
  schema_change_jobs: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'target_type',
      'target_id',
      'model_id',
      'from_revision_id',
      'to_revision_id',
      'status',
      'plan',
      'job_id',
      'error',
      'requested_by_type',
      'requested_by_id',
      'created_at',
      'updated_at',
      'finished_at',
      'change_set_id',
    ],
    nullable: [
      'model_id',
      'from_revision_id',
      'to_revision_id',
      'job_id',
      'error',
      'requested_by_id',
      'finished_at',
      'change_set_id',
    ],
    timestamps: ['created_at', 'updated_at', 'finished_at'],
    uniqueKeys: [
      { name: 'schema_change_jobs_in_flight_uq', columns: ['target_type', 'target_id'] },
      { name: 'schema_change_jobs_pkey', columns: ['id'] },
    ],
  },
  schema_drafts: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'change_set_id',
      'definition_id',
      'kind',
      'api_key',
      'base_version',
      'definition',
      'version',
      'updated_by_type',
      'updated_by_id',
      'created_at',
      'updated_at',
      'shared',
    ],
    nullable: ['base_version', 'definition', 'updated_by_id'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'schema_drafts_pkey', columns: ['id'] },
      { name: 'schema_drafts_set_definition_uq', columns: ['change_set_id', 'definition_id'] },
    ],
  },
  schema_revisions: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'model_id',
      'version',
      'definition',
      'hash',
      'parent_revision_id',
      'created_by_type',
      'created_by_id',
      'created_at',
    ],
    nullable: ['parent_revision_id', 'created_by_id'],
    timestamps: ['created_at'],
    uniqueKeys: [
      { name: 'schema_revisions_model_version_uq', columns: ['model_id', 'version'] },
      { name: 'schema_revisions_pkey', columns: ['id'] },
    ],
  },
  schema_settings: {
    primaryKey: ['id'],
    columns: ['id', 'read_only', 'read_only_reason', 'updated_by_type', 'updated_by_id', 'updated_at'],
    nullable: ['read_only_reason', 'updated_by_type', 'updated_by_id'],
    timestamps: ['updated_at'],
    uniqueKeys: [{ name: 'schema_settings_pkey', columns: ['id'] }],
  },
  setup_tokens: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'token_hash', 'used_at', 'superseded_at', 'created_at', 'updated_at'],
    nullable: ['used_at', 'superseded_at'],
    timestamps: ['used_at', 'superseded_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'setup_tokens_pkey', columns: ['id'] },
      { name: 'setup_tokens_token_hash_key', columns: ['token_hash'] },
    ],
  },
  site_app_roles: {
    primaryKey: ['site_id', 'audience', 'role_id'],
    columns: ['site_id', 'audience', 'role_id', 'created_at'],
    nullable: [],
    timestamps: ['created_at'],
    uniqueKeys: [{ name: 'site_app_roles_pkey', columns: ['site_id', 'audience', 'role_id'] }],
  },
  sites: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: ['id', 'key', 'name', 'is_primary', 'version', 'created_at', 'updated_at', 'seo_defaults'],
    nullable: ['seo_defaults'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'sites_key_key', columns: ['key'] },
      { name: 'sites_pkey', columns: ['id'] },
      { name: 'sites_single_primary_uq', columns: ['is_primary'] },
    ],
  },
  system_settings: {
    primaryKey: ['key'],
    columns: ['key', 'value', 'updated_at'],
    nullable: [],
    timestamps: ['updated_at'],
    uniqueKeys: [{ name: 'system_settings_pkey', columns: ['key'] }],
  },
  system_versions: {
    primaryKey: ['id'],
    columns: ['id', 'schema_version', 'permissions_version', 'updated_at'],
    nullable: [],
    timestamps: ['updated_at'],
    uniqueKeys: [{ name: 'system_versions_pkey', columns: ['id'] }],
  },
  token_reads: {
    primaryKey: ['day', 'site_id', 'principal_key'],
    columns: ['day', 'principal_key', 'requests', 'last_snapshot', 'last_read_at', 'site_id'],
    nullable: ['last_snapshot'],
    timestamps: ['last_read_at'],
    uniqueKeys: [{ name: 'token_reads_pkey', columns: ['day', 'site_id', 'principal_key'] }],
  },
  unique_values: {
    primaryKey: ['site_id', 'field_id', 'locale', 'state', 'value_hash'],
    columns: ['field_id', 'locale', 'state', 'value_hash', 'entry_id', 'model_id', 'site_id'],
    nullable: [],
    uniqueKeys: [
      { name: 'unique_values_pkey', columns: ['site_id', 'field_id', 'locale', 'state', 'value_hash'] },
    ],
  },
  webhook_deliveries: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'webhook_id',
      'event_id',
      'event_type',
      'payload',
      'is_test',
      'status',
      'attempts',
      'last_response_status',
      'last_error',
      'attempt_log',
      'job_id',
      'delivered_at',
      'created_at',
      'updated_at',
    ],
    nullable: ['event_id', 'last_response_status', 'last_error', 'job_id', 'delivered_at'],
    timestamps: ['delivered_at', 'created_at', 'updated_at'],
    uniqueKeys: [
      { name: 'webhook_deliveries_event_uq', columns: ['webhook_id', 'event_id'] },
      { name: 'webhook_deliveries_pkey', columns: ['id'] },
    ],
  },
  webhooks: {
    primaryKey: ['id'],
    generated: { id: 'uuid' },
    columns: [
      'id',
      'name',
      'url',
      'events',
      'enabled',
      'secret_encrypted',
      'allow_private_network',
      'max_attempts',
      'version',
      'created_by',
      'created_at',
      'updated_at',
      'site_id',
    ],
    nullable: ['created_by', 'site_id'],
    timestamps: ['created_at', 'updated_at'],
    uniqueKeys: [{ name: 'webhooks_pkey', columns: ['id'] }],
  },
  advisory_locks: {
    primaryKey: ['namespace', 'lock_key'],
    columns: ['namespace', 'lock_key'],
    nullable: [],
    uniqueKeys: [{ name: 'advisory_locks_pkey', columns: ['namespace', 'lock_key'] }],
  },
  notifications: {
    primaryKey: ['id'],
    identity: 'id',
    columns: ['id', 'channel', 'payload', 'created_at'],
    nullable: [],
    timestamps: ['created_at'],
    uniqueKeys: [{ name: 'notifications_pkey', columns: ['id'] }],
  },
  sequence_entry_heads_change_seq: {
    primaryKey: ['value'],
    identity: 'value',
    columns: ['value'],
    nullable: [],
    uniqueKeys: [{ name: 'sequence_entry_heads_change_seq_pkey', columns: ['value'] }],
  },
};

/** The table's metadata, or undefined for a table Shapio does not own (tests' own tables). */
export const tableInfo = (table: string): MysqlTableInfo | undefined => MYSQL_TABLES[table];
