import { sql, type Kysely } from 'kysely';

/**
 * MySQL baseline: Shapio's whole system schema as of PostgreSQL migration
 * `20261003160000_create_assist_runs`, in one step, with the rows those migrations seed. Later migrations
 * follow the twin rule (`./index.ts`).
 *
 * Written from the migrated PostgreSQL catalog (types in `db/mysql/codec.ts`), then kept honest by
 * `test/mysqlBaseline.int.test.ts`, which migrates both databases and compares the logical schema and the
 * seeded rows. Differences that are deliberate:
 * - Tables default to `utf8mb4` with the binary `utf8mb4_0900_bin` collation (case-sensitive, NO PAD,
 *   code point order); UUIDs are `CHAR(36)` ASCII with a case-insensitive collation, like PostgreSQL's uuid
 *   input. Text in a key or index is `VARCHAR(n)` (`LONGTEXT` cannot be indexed whole); other text is
 *   `LONGTEXT`.
 * - Partial unique indexes are unique indexes on `(case when <predicate> then <column> end)` key parts:
 *   MySQL has no partial index, and a NULL key part never conflicts. Partial non-unique indexes are plain.
 *   The three `NULLS NOT DISTINCT` constraints index `coalesce(column, '')`.
 * - `entry_heads_data_gin` (GIN, containment) has no MySQL equivalent and is left out.
 * - `entry_heads.change_seq` has no default: the MySQL plugin fills it from
 *   `sequence_entry_heads_change_seq` (AUTO_INCREMENT, no lock held to commit). UUID keys default to
 *   `uuid()` but the plugin fills them first (v4, known before the insert, for emulated RETURNING).
 * - `media_assets_folder_id_fkey` sets only `folder_id` to null on delete (PostgreSQL's column list),
 *   which MySQL expresses as a trigger; immutability triggers signal SQLSTATE 45000. With binary logging
 *   on, creating triggers needs SUPER or `log_bin_trust_function_creators = 1` (documentation/mysql.md).
 * - `editor_presence` is a plain table (UNLOGGED has no MySQL meaning).
 * - MySQL-only tables: `advisory_locks` (transaction-level advisory locks as row locks),
 *   `notifications` (LISTEN/NOTIFY as a polled table), `sequence_entry_heads_change_seq`.
 * - Identity keys are `AUTO_INCREMENT`. MySQL creates an index for a foreign key no index covers.
 * MySQL runs DDL outside transactions: if the baseline fails part-way, drop the database's tables and
 * migrate again.
 */
const STATEMENTS: readonly string[] = [
  `create table \`system_versions\` (
  \`id\` tinyint(1) not null default 1,
  \`schema_version\` int not null default 0,
  \`permissions_version\` int not null default 0,
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`system_versions_pkey\` primary key (\`id\`),
  constraint \`system_versions_id_check\` check (\`id\` = 1)
)`,
  `create table \`jobs\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`type\` longtext not null,
  \`payload\` json not null default (json_object()),
  \`status\` longtext not null default ('pending'),
  \`priority\` int not null default 0,
  \`run_at\` datetime(6) not null default current_timestamp(6),
  \`attempts\` int not null default 0,
  \`max_attempts\` int not null default 10,
  \`idempotency_key\` varchar(512),
  \`locked_by\` longtext,
  \`locked_until\` datetime(6),
  \`checkpoint\` json,
  \`result\` json,
  \`last_error\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`finished_at\` datetime(6),
  constraint \`jobs_pkey\` primary key (\`id\`),
  constraint \`jobs_max_attempts_check\` check ((\`max_attempts\` > 0)),
  constraint \`jobs_status_check\` check ((\`status\` in ('pending', 'running', 'succeeded', 'dead')))
)`,
  `create table \`outbox_events\` (
  \`id\` bigint not null auto_increment,
  \`event_id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`type\` longtext not null,
  \`aggregate_type\` longtext not null,
  \`aggregate_id\` longtext not null,
  \`payload\` json not null default (json_object()),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`dispatched_at\` datetime(6),
  \`dispatch_attempts\` int not null default 0,
  \`last_dispatch_error\` longtext,
  \`site_id\` char(36) character set ascii collate ascii_general_ci,
  unique key \`outbox_events_event_id_key\` (\`event_id\`),
  constraint \`outbox_events_pkey\` primary key (\`id\`)
)`,
  `create table \`audit_events\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`occurred_at\` datetime(6) not null default current_timestamp(6),
  \`actor_type\` varchar(64) not null,
  \`actor_id\` varchar(255),
  \`action\` longtext not null,
  \`target_type\` varchar(64),
  \`target_id\` varchar(255),
  \`outcome\` longtext not null,
  \`request_id\` longtext,
  \`ip\` longtext,
  \`metadata\` json not null default (json_object()),
  \`site_id\` char(36) character set ascii collate ascii_general_ci,
  constraint \`audit_events_pkey\` primary key (\`id\`),
  constraint \`audit_events_actor_type_check\` check ((\`actor_type\` in ('admin', 'app_user', 'token', 'anonymous', 'system'))),
  constraint \`audit_events_outcome_check\` check ((\`outcome\` in ('success', 'failure')))
)`,
  `create table \`admin_users\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`email\` varchar(255) not null,
  \`name\` longtext not null default (''),
  \`password_hash\` longtext not null,
  \`status\` longtext not null default ('active'),
  \`last_login_at\` datetime(6),
  \`password_changed_at\` datetime(6) not null default current_timestamp(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`admin_users_email_key\` (\`email\`),
  constraint \`admin_users_pkey\` primary key (\`id\`),
  constraint \`admin_users_status_check\` check ((\`status\` in ('active', 'disabled')))
)`,
  `create table \`admin_roles\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`key\` varchar(64) not null,
  \`name\` longtext not null,
  \`description\` longtext not null default (''),
  \`kind\` longtext not null default ('admin'),
  \`is_system\` tinyint(1) not null default 0,
  \`version\` int not null default 1,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`admin_roles_key_key\` (\`key\`),
  constraint \`admin_roles_pkey\` primary key (\`id\`),
  constraint \`admin_roles_key_check\` check ((regexp_like(\`key\`, '^[a-z][a-z0-9-]{0,62}$', 'c'))),
  constraint \`admin_roles_kind_check\` check ((\`kind\` in ('admin', 'delivery')))
)`,
  `create table \`admin_role_permissions\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`action\` varchar(64) not null,
  \`model_id\` varchar(255),
  \`condition\` longtext,
  \`field_ids\` json,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`admin_role_permissions_grant_uq\` (\`role_id\`, \`action\`, (coalesce(\`model_id\`, ''))),
  constraint \`admin_role_permissions_pkey\` primary key (\`id\`),
  constraint \`admin_role_permissions_condition_check\` check ((\`condition\` = 'ownedByPrincipal'))
)`,
  `create table \`admin_user_roles\` (
  \`admin_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci,
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  unique key \`admin_user_roles_assignment_uq\` (\`admin_user_id\`, \`role_id\`, (coalesce(\`site_id\`, ''))),
  constraint \`admin_user_roles_pk\` primary key (\`id\`)
)`,
  `create table \`admin_sessions\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`admin_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`token_hash\` varchar(128) not null,
  \`csrf_secret\` longtext not null,
  \`ip\` longtext,
  \`user_agent\` longtext,
  \`last_seen_at\` datetime(6) not null default current_timestamp(6),
  \`expires_at\` datetime(6) not null,
  \`revoked_at\` datetime(6),
  \`rotation_required\` tinyint(1) not null default 0,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`admin_sessions_token_hash_key\` (\`token_hash\`),
  constraint \`admin_sessions_pkey\` primary key (\`id\`)
)`,
  `create table \`admin_invitations\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`email\` varchar(255) not null,
  \`token_hash\` varchar(128),
  \`invited_by\` char(36) character set ascii collate ascii_general_ci,
  \`expires_at\` datetime(6) not null,
  \`accepted_at\` datetime(6),
  \`revoked_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`role_assignments\` json not null default (json_array()),
  unique key \`admin_invitations_token_hash_key\` (\`token_hash\`),
  constraint \`admin_invitations_pkey\` primary key (\`id\`)
)`,
  `create table \`password_resets\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`admin_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`token_hash\` varchar(128),
  \`expires_at\` datetime(6) not null,
  \`used_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`password_resets_token_hash_key\` (\`token_hash\`),
  constraint \`password_resets_pkey\` primary key (\`id\`)
)`,
  `create table \`setup_tokens\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`token_hash\` varchar(128) not null,
  \`used_at\` datetime(6),
  \`superseded_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`setup_tokens_token_hash_key\` (\`token_hash\`),
  constraint \`setup_tokens_pkey\` primary key (\`id\`)
)`,
  `create table \`api_tokens\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`name\` longtext not null,
  \`token_hash\` varchar(128) not null,
  \`token_prefix\` longtext not null,
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`expires_at\` datetime(6),
  \`last_used_at\` datetime(6),
  \`revoked_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci,
  unique key \`api_tokens_token_hash_key\` (\`token_hash\`),
  constraint \`api_tokens_pkey\` primary key (\`id\`)
)`,
  `create table \`system_settings\` (
  \`key\` varchar(64) not null,
  \`value\` longtext not null,
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`system_settings_pkey\` primary key (\`key\`)
)`,
  `create table \`models\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null,
  \`kind\` longtext not null,
  \`api_key\` varchar(255) not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`deleted_at\` datetime(6),
  constraint \`models_pkey\` primary key (\`id\`),
  constraint \`models_kind_check\` check ((\`kind\` in ('collection', 'singleton', 'component')))
)`,
  `create table \`schema_revisions\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`version\` int not null,
  \`definition\` json not null,
  \`hash\` longtext not null,
  \`parent_revision_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_by_type\` longtext not null,
  \`created_by_id\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  unique key \`schema_revisions_model_version_uq\` (\`model_id\`, \`version\`),
  constraint \`schema_revisions_pkey\` primary key (\`id\`),
  constraint \`schema_revisions_version_check\` check ((\`version\` > 0))
)`,
  `create table \`model_active_versions\` (
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`revision_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`version\` int not null,
  \`schema_version\` int not null,
  \`activated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`model_active_versions_pkey\` primary key (\`model_id\`)
)`,
  `create table \`schema_change_jobs\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`target_type\` varchar(64) not null,
  \`target_id\` varchar(255) not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci,
  \`from_revision_id\` char(36) character set ascii collate ascii_general_ci,
  \`to_revision_id\` char(36) character set ascii collate ascii_general_ci,
  \`status\` longtext not null default ('pending'),
  \`plan\` json not null default (json_object()),
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`error\` json,
  \`requested_by_type\` longtext not null,
  \`requested_by_id\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`finished_at\` datetime(6),
  \`change_set_id\` char(36) character set ascii collate ascii_general_ci,
  constraint \`schema_change_jobs_pkey\` primary key (\`id\`),
  constraint \`schema_change_jobs_status_check\` check ((\`status\` in ('pending', 'running', 'activated', 'failed', 'cancelled'))),
  constraint \`schema_change_jobs_target_type_check\` check ((\`target_type\` in ('model', 'locale')))
)`,
  `create table \`locales\` (
  \`code\` varchar(64) not null,
  \`label\` longtext not null,
  \`is_default\` tinyint(1) not null default 0,
  \`fallbacks\` json not null default (json_array()),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`locales_pkey\` primary key (\`code\`)
)`,
  `create table \`schema_settings\` (
  \`id\` tinyint(1) not null default 1,
  \`read_only\` tinyint(1) not null default 0,
  \`read_only_reason\` longtext,
  \`updated_by_type\` longtext,
  \`updated_by_id\` longtext,
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`schema_settings_pkey\` primary key (\`id\`),
  constraint \`schema_settings_id_check\` check (\`id\` = 1)
)`,
  `create table \`entries\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`owner_app_user_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_by_admin_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`deleted_at\` datetime(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`entries_id_site_uq\` (\`id\`, \`site_id\`),
  constraint \`entries_pkey\` primary key (\`id\`)
)`,
  `create table \`content_revisions\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`schema_revision_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`data\` json not null,
  \`reason\` longtext not null,
  \`author_type\` longtext not null,
  \`author_id\` longtext,
  \`parent_revision_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  constraint \`content_revisions_pkey\` primary key (\`id\`),
  constraint \`content_revisions_reason_check\` check ((\`reason\` in ('create', 'save', 'publish', 'restore', 'duplicate', 'localize', 'conversion')))
)`,
  `create table \`entry_heads\` (
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`state\` varchar(64) not null,
  \`revision_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`data\` json not null,
  \`autosaved_at\` datetime(6),
  \`version\` int not null default 1,
  \`change_seq\` bigint not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`entry_heads_pkey\` primary key (\`entry_id\`, \`locale\`, \`state\`),
  constraint \`entry_heads_state_check\` check ((\`state\` in ('draft', 'published')))
)`,
  `create table \`relation_edges\` (
  \`source_entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`state\` varchar(64) not null,
  \`field_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`position\` int not null,
  \`target_entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`relation_edges_pkey\` primary key (\`source_entry_id\`, \`locale\`, \`state\`, \`field_id\`, \`position\`)
)`,
  `create table \`unique_values\` (
  \`field_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`state\` varchar(64) not null,
  \`value_hash\` varchar(128) not null,
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`unique_values_pkey\` primary key (\`site_id\`, \`field_id\`, \`locale\`, \`state\`, \`value_hash\`),
  constraint \`unique_values_state_check\` check ((\`state\` in ('draft', 'published')))
)`,
  `create table \`publication_state\` (
  \`last_seq\` bigint not null default 0,
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`publication_state_pkey\` primary key (\`site_id\`)
)`,
  `create table \`publication_log\` (
  \`id\` bigint not null auto_increment,
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`revision_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`from_seq\` bigint not null,
  \`to_seq\` bigint,
  \`published_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`publication_log_pkey\` primary key (\`id\`)
)`,
  `create table \`media_folders\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`parent_id\` char(36) character set ascii collate ascii_general_ci,
  \`name\` varchar(255) not null,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`version\` int not null default 1,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`media_folders_id_site_uq\` (\`id\`, \`site_id\`),
  constraint \`media_folders_pkey\` primary key (\`id\`),
  constraint \`media_folders_name_check\` check (((char_length(\`name\`) >= 1) AND (char_length(\`name\`) <= 255)))
)`,
  `create table \`media_assets\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null,
  \`folder_id\` char(36) character set ascii collate ascii_general_ci,
  \`storage_driver\` varchar(64) not null,
  \`storage_key\` varchar(768) not null,
  \`original_filename\` longtext not null,
  \`mime_type\` longtext not null,
  \`size_bytes\` bigint not null,
  \`width\` int,
  \`height\` int,
  \`checksum_sha256\` longtext,
  \`alt\` longtext not null default (''),
  \`caption\` longtext not null default (''),
  \`focal_x\` float,
  \`focal_y\` float,
  \`visibility\` longtext not null default ('public'),
  \`status\` longtext not null default ('processing'),
  \`processing_error\` longtext,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`version\` int not null default 1,
  \`deleted_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`media_assets_pkey\` primary key (\`id\`),
  constraint \`media_assets_focal_point_ck\` check (((\`focal_x\` IS NULL) = (\`focal_y\` IS NULL))),
  constraint \`media_assets_focal_x_check\` check (((\`focal_x\` >= (0)) AND (\`focal_x\` <= (1)))),
  constraint \`media_assets_focal_y_check\` check (((\`focal_y\` >= (0)) AND (\`focal_y\` <= (1)))),
  constraint \`media_assets_status_check\` check ((\`status\` in ('processing', 'ready', 'failed'))),
  constraint \`media_assets_storage_driver_check\` check ((\`storage_driver\` in ('local', 's3'))),
  constraint \`media_assets_visibility_check\` check ((\`visibility\` in ('public', 'private')))
)`,
  `create table \`media_variants\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`asset_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`name\` varchar(255) not null,
  \`width\` int,
  \`height\` int,
  \`format\` longtext not null,
  \`mime_type\` longtext not null,
  \`storage_key\` varchar(768),
  \`size_bytes\` bigint,
  \`checksum_sha256\` longtext,
  \`status\` longtext not null default ('pending'),
  \`error\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`media_variants_asset_name_uq\` (\`asset_id\`, \`name\`),
  constraint \`media_variants_pkey\` primary key (\`id\`),
  constraint \`media_variants_status_check\` check ((\`status\` in ('pending', 'ready', 'failed')))
)`,
  `create table \`media_references\` (
  \`asset_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`field_id\` varchar(255) not null,
  \`locale\` varchar(64) not null,
  \`state\` varchar(64) not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  constraint \`media_references_pk\` primary key (\`asset_id\`, \`entry_id\`, \`locale\`, \`state\`, \`field_id\`),
  constraint \`media_references_state_check\` check ((\`state\` in ('draft', 'published')))
)`,
  `create table \`media_upload_grants\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`asset_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`kind\` longtext not null,
  \`storage_driver\` longtext not null,
  \`storage_key\` varchar(768) not null,
  \`original_filename\` longtext not null,
  \`declared_mime_type\` longtext not null,
  \`max_size_bytes\` bigint not null,
  \`folder_id\` char(36) character set ascii collate ascii_general_ci,
  \`visibility\` longtext not null,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_by_principal\` longtext not null,
  \`status\` longtext not null default ('pending'),
  \`expires_at\` datetime(6) not null,
  \`consumed_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`media_upload_grants_storage_key_key\` (\`storage_key\`),
  constraint \`media_upload_grants_pkey\` primary key (\`id\`),
  constraint \`media_upload_grants_kind_check\` check ((\`kind\` in ('create', 'replace'))),
  constraint \`media_upload_grants_status_check\` check ((\`status\` in ('pending', 'consumed', 'rejected', 'expired'))),
  constraint \`media_upload_grants_storage_driver_check\` check ((\`storage_driver\` in ('local', 's3'))),
  constraint \`media_upload_grants_visibility_check\` check ((\`visibility\` in ('public', 'private')))
)`,
  `create table \`scheduled_publications\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`action\` longtext not null,
  \`run_at\` datetime(6) not null,
  \`status\` varchar(64) not null default 'scheduled',
  \`created_by_token\` char(36) character set ascii collate ascii_general_ci,
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`snapshot_seq\` bigint,
  \`error\` longtext,
  \`executed_at\` datetime(6),
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`scheduled_publications_pkey\` primary key (\`id\`),
  constraint \`scheduled_publications_action_check\` check ((\`action\` in ('publish', 'unpublish'))),
  constraint \`scheduled_publications_status_check\` check ((\`status\` in ('scheduled', 'done', 'failed', 'cancelled')))
)`,
  `create table \`webhooks\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`name\` longtext not null,
  \`url\` longtext not null,
  \`events\` json not null default (json_array()),
  \`enabled\` tinyint(1) not null default 1,
  \`secret_encrypted\` longtext not null,
  \`allow_private_network\` tinyint(1) not null default 0,
  \`max_attempts\` int not null default 8,
  \`version\` int not null default 1,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci,
  constraint \`webhooks_pkey\` primary key (\`id\`),
  constraint \`webhooks_max_attempts_check\` check (((\`max_attempts\` >= 1) AND (\`max_attempts\` <= 20))),
  constraint \`webhooks_name_check\` check (((char_length(\`name\`) >= 1) AND (char_length(\`name\`) <= 200)))
)`,
  `create table \`webhook_deliveries\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`webhook_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`event_id\` char(36) character set ascii collate ascii_general_ci,
  \`event_type\` longtext not null,
  \`payload\` json not null,
  \`is_test\` tinyint(1) not null default 0,
  \`status\` longtext not null default ('pending'),
  \`attempts\` int not null default 0,
  \`last_response_status\` int,
  \`last_error\` longtext,
  \`attempt_log\` json not null default (json_array()),
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`delivered_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  constraint \`webhook_deliveries_pkey\` primary key (\`id\`),
  constraint \`webhook_deliveries_status_check\` check ((\`status\` in ('pending', 'retrying', 'succeeded', 'dead')))
)`,
  `create table \`deployment_connections\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`name\` longtext not null,
  \`provider\` longtext not null,
  \`settings\` json not null default (json_object()),
  \`secrets_encrypted\` longtext not null,
  \`secret_env_refs\` json not null default (json_object()),
  \`delivery_role_id\` char(36) character set ascii collate ascii_general_ci,
  \`preview_url_template\` longtext,
  \`trigger_policy\` json not null default (json_array()),
  \`debounce_seconds\` int not null default 10,
  \`allow_private_network\` tinyint(1) not null default 0,
  \`enabled\` tinyint(1) not null default 1,
  \`version\` int not null default 1,
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`deployment_connections_pkey\` primary key (\`id\`),
  constraint \`deployment_connections_debounce_seconds_check\` check (((\`debounce_seconds\` >= 0) AND (\`debounce_seconds\` <= 3600))),
  constraint \`deployment_connections_name_check\` check (((char_length(\`name\`) >= 1) AND (char_length(\`name\`) <= 200))),
  constraint \`deployment_connections_provider_check\` check ((\`provider\` in ('generic_webhook', 'cloudflare_pages', 'vercel', 'netlify', 'github')))
)`,
  `create table \`deployment_runs\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`connection_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`status\` longtext not null default ('queued'),
  \`status_rank\` int not null default 0,
  \`trigger\` longtext not null,
  \`snapshot_seq\` bigint,
  \`schema_version\` int,
  \`retry_of\` char(36) character set ascii collate ascii_general_ci,
  \`provider_ref\` longtext,
  \`log_url\` longtext,
  \`site_url\` longtext,
  \`error\` longtext,
  \`timeline\` json not null default (json_array()),
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`triggered_at\` datetime(6),
  \`finished_at\` datetime(6),
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`change_set_id\` char(36) character set ascii collate ascii_general_ci,
  constraint \`deployment_runs_pkey\` primary key (\`id\`),
  constraint \`deployment_runs_status_check\` check ((\`status\` in ('queued', 'triggered', 'building', 'deployed', 'failed', 'unknown'))),
  constraint \`deployment_runs_trigger_check\` check ((\`trigger\` in ('publish', 'change_set', 'schema', 'manual', 'retry')))
)`,
  `create table \`preview_tokens\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`token_hash\` varchar(128) not null,
  \`token_prefix\` longtext not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` longtext,
  \`connection_id\` char(36) character set ascii collate ascii_general_ci,
  \`delivery_role_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_by\` char(36) character set ascii collate ascii_general_ci not null,
  \`expires_at\` datetime(6) not null,
  \`revoked_at\` datetime(6),
  \`last_used_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`preview_tokens_token_hash_key\` (\`token_hash\`),
  constraint \`preview_tokens_pkey\` primary key (\`id\`)
)`,
  `create table \`app_users\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`email\` varchar(255) not null,
  \`name\` longtext not null default (''),
  \`password_hash\` longtext,
  \`confirmed_at\` datetime(6),
  \`blocked_at\` datetime(6),
  \`last_login_at\` datetime(6),
  \`password_changed_at\` datetime(6),
  \`deleted_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`token_version\` int not null default 0,
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`app_users_pkey\` primary key (\`id\`)
)`,
  `create table \`app_roles\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`key\` varchar(64) not null,
  \`name\` longtext not null,
  \`description\` longtext not null default (''),
  \`is_system\` tinyint(1) not null default 0,
  \`version\` int not null default 1,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`app_roles_key_key\` (\`key\`),
  constraint \`app_roles_pkey\` primary key (\`id\`),
  constraint \`app_roles_key_check\` check ((regexp_like(\`key\`, '^[a-z][a-z0-9-]{0,62}$', 'c')))
)`,
  `create table \`app_role_permissions\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`action\` varchar(64) not null,
  \`model_id\` varchar(255),
  \`condition\` longtext,
  \`field_ids\` json,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`app_role_permissions_grant_uq\` (\`role_id\`, \`action\`, (coalesce(\`model_id\`, ''))),
  constraint \`app_role_permissions_pkey\` primary key (\`id\`),
  constraint \`app_role_permissions_action_check\` check ((\`action\` in ('read', 'create', 'update', 'delete', 'publish'))),
  constraint \`app_role_permissions_condition_check\` check ((\`condition\` = 'ownedByPrincipal'))
)`,
  `create table \`app_user_roles\` (
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`app_user_roles_pk\` primary key (\`app_user_id\`, \`role_id\`)
)`,
  `create table \`app_refresh_tokens\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`family_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`token_hash\` varchar(128) not null,
  \`expires_at\` datetime(6) not null,
  \`used_at\` datetime(6),
  \`reuse_grace_used_at\` datetime(6),
  \`revoked_at\` datetime(6),
  \`revoked_reason\` longtext,
  \`ip\` longtext,
  \`user_agent\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  unique key \`app_refresh_tokens_token_hash_key\` (\`token_hash\`),
  constraint \`app_refresh_tokens_pkey\` primary key (\`id\`)
)`,
  `create table \`app_oauth_accounts\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`provider\` varchar(64) not null,
  \`provider_user_id\` varchar(255) not null,
  \`email\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`app_oauth_accounts_identity_uq\` (\`site_id\`, \`provider\`, \`provider_user_id\`),
  constraint \`app_oauth_accounts_pkey\` primary key (\`id\`),
  constraint \`app_oauth_accounts_provider_check\` check ((\`provider\` in ('google', 'github')))
)`,
  `create table \`email_confirmations\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`email\` longtext not null,
  \`token_hash\` varchar(128),
  \`expires_at\` datetime(6) not null,
  \`used_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`email_confirmations_token_hash_key\` (\`token_hash\`),
  constraint \`email_confirmations_pkey\` primary key (\`id\`)
)`,
  `create table \`app_password_resets\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`email\` longtext not null,
  \`token_hash\` varchar(128),
  \`expires_at\` datetime(6) not null,
  \`used_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`app_password_resets_token_hash_key\` (\`token_hash\`),
  constraint \`app_password_resets_pkey\` primary key (\`id\`)
)`,
  `create table \`app_login_codes\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`app_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`code_hash\` varchar(128) not null,
  \`expires_at\` datetime(6) not null,
  \`used_at\` datetime(6),
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`code_challenge\` longtext not null,
  unique key \`app_login_codes_code_hash_key\` (\`code_hash\`),
  constraint \`app_login_codes_pkey\` primary key (\`id\`)
)`,
  `create table \`extension_hook_runs\` (
  \`event_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`hook\` varchar(255) not null,
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`completed_at\` datetime(6) not null default current_timestamp(6),
  constraint \`extension_hook_runs_pkey\` primary key (\`event_id\`, \`hook\`)
)`,
  `create table \`field_reads\` (
  \`day\` date not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`field_path\` varchar(400) not null,
  \`principal_key\` varchar(255) not null,
  \`selection\` varchar(64) not null,
  \`reads\` bigint not null default 0,
  \`last_read_at\` datetime(6) not null,
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`field_reads_pkey\` primary key (\`day\`, \`site_id\`, \`model_id\`, \`field_path\`, \`principal_key\`, \`selection\`),
  constraint \`field_reads_selection_check\` check ((\`selection\` in ('explicit', 'implicit')))
)`,
  `create table \`token_reads\` (
  \`day\` date not null,
  \`principal_key\` varchar(255) not null,
  \`requests\` bigint not null default 0,
  \`last_snapshot\` bigint,
  \`last_read_at\` datetime(6) not null,
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`token_reads_pkey\` primary key (\`day\`, \`site_id\`, \`principal_key\`)
)`,
  `create table \`change_sets\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`title\` longtext not null,
  \`description\` longtext not null default (''),
  \`status\` varchar(64) not null default 'open',
  \`ship_phase\` longtext,
  \`source\` longtext not null default ('manual'),
  \`restore_of_seq\` bigint,
  \`scheduled_for\` datetime(6),
  \`schedule_job_id\` char(36) character set ascii collate ascii_general_ci,
  \`scheduled_by\` char(36) character set ascii collate ascii_general_ci,
  \`scheduled_by_token\` char(36) character set ascii collate ascii_general_ci,
  \`ship_job_id\` char(36) character set ascii collate ascii_general_ci,
  \`ship_mode\` longtext,
  \`ship_requested_by\` char(36) character set ascii collate ascii_general_ci,
  \`ship_requested_by_token\` char(36) character set ascii collate ascii_general_ci,
  \`acknowledge_breaking\` tinyint(1) not null default 0,
  \`acknowledge_destructive\` tinyint(1) not null default 0,
  \`deployment_connection_id\` char(36) character set ascii collate ascii_general_ci,
  \`deployment_run_id\` char(36) character set ascii collate ascii_general_ci,
  \`shipped_at\` datetime(6),
  \`shipped_seq\` bigint,
  \`schema_version_after\` int,
  \`error\` json,
  \`restore_report\` json not null default (json_array()),
  \`created_by\` char(36) character set ascii collate ascii_general_ci,
  \`created_by_token\` char(36) character set ascii collate ascii_general_ci,
  \`version\` int not null default 1,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`change_sets_id_site_uq\` (\`id\`, \`site_id\`),
  constraint \`change_sets_pkey\` primary key (\`id\`),
  constraint \`change_sets_ship_mode_check\` check ((\`ship_mode\` in ('interactive', 'scheduled'))),
  constraint \`change_sets_ship_phase_check\` check ((\`ship_phase\` in ('preparing', 'activating'))),
  constraint \`change_sets_source_check\` check ((\`source\` in ('manual', 'release', 'restore', 'builder', 'assist'))),
  constraint \`change_sets_status_check\` check ((\`status\` in ('open', 'scheduled', 'shipping', 'shipped', 'failed', 'discarded'))),
  constraint \`change_sets_title_check\` check (((char_length(\`title\`) >= 1) AND (char_length(\`title\`) <= 200)))
)`,
  `create table \`schema_drafts\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`change_set_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`definition_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`kind\` longtext not null,
  \`api_key\` longtext not null,
  \`base_version\` int,
  \`definition\` json,
  \`version\` int not null default 1,
  \`updated_by_type\` longtext not null,
  \`updated_by_id\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`schema_drafts_set_definition_uq\` (\`change_set_id\`, \`definition_id\`),
  constraint \`schema_drafts_pkey\` primary key (\`id\`),
  constraint \`schema_drafts_kind_check\` check ((\`kind\` in ('collection', 'singleton', 'component')))
)`,
  `create table \`change_set_items\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`change_set_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`kind\` longtext not null,
  \`position\` int not null,
  \`entry_id\` char(36) character set ascii collate ascii_general_ci,
  \`model_id\` char(36) character set ascii collate ascii_general_ci,
  \`locale\` varchar(64),
  \`action\` longtext,
  \`source_revision_id\` char(36) character set ascii collate ascii_general_ci,
  \`schema_draft_id\` char(36) character set ascii collate ascii_general_ci,
  \`status\` longtext not null default ('pending'),
  \`error\` longtext,
  \`ship_state\` json,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`change_set_items_pkey\` primary key (\`id\`),
  constraint \`change_set_items_action_check\` check ((\`action\` in ('publish', 'unpublish'))),
  constraint \`change_set_items_kind_check\` check ((\`kind\` in ('entry', 'schema'))),
  constraint \`change_set_items_shape_check\` check ((((\`kind\` = 'entry') AND (\`entry_id\` IS NOT NULL) AND (\`model_id\` IS NOT NULL) AND (\`locale\` IS NOT NULL) AND (\`action\` IS NOT NULL) AND (\`schema_draft_id\` IS NULL)) OR ((\`kind\` = 'schema') AND (\`schema_draft_id\` IS NOT NULL) AND (\`entry_id\` IS NULL) AND (\`source_revision_id\` IS NULL)))),
  constraint \`change_set_items_status_check\` check ((\`status\` in ('pending', 'done', 'failed')))
)`,
  `create table \`publication_snapshots\` (
  \`seq\` bigint not null,
  \`schema_version\` int,
  \`source\` longtext not null,
  \`change_set_id\` char(36) character set ascii collate ascii_general_ci,
  \`actor_type\` longtext,
  \`actor_id\` longtext,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  constraint \`publication_snapshots_pkey\` primary key (\`site_id\`, \`seq\`)
)`,
  `create table \`editor_presence\` (
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`admin_user_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`tab_id\` varchar(64) not null,
  \`locale\` longtext,
  \`started_at\` datetime(6) not null default current_timestamp(6),
  \`last_seen_at\` datetime(6) not null default current_timestamp(6),
  constraint \`editor_presence_pkey\` primary key (\`entry_id\`, \`admin_user_id\`, \`tab_id\`),
  constraint \`editor_presence_tab_id_check\` check (((char_length(\`tab_id\`) >= 1) AND (char_length(\`tab_id\`) <= 64)))
)`,
  `create table \`content_health_findings\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`entry_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`model_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`locale\` varchar(64) not null,
  \`rule\` varchar(255) not null,
  \`subject\` varchar(255) not null default '',
  \`severity\` longtext not null,
  \`path\` longtext,
  \`details\` json not null default (json_object()),
  \`first_seen_at\` datetime(6) not null default current_timestamp(6),
  \`last_seen_at\` datetime(6) not null default current_timestamp(6),
  \`resolved_at\` datetime(6),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  unique key \`content_health_findings_entry_id_locale_rule_subject_key\` (\`entry_id\`, \`locale\`, \`rule\`, \`subject\`),
  constraint \`content_health_findings_pkey\` primary key (\`id\`),
  constraint \`content_health_findings_severity_check\` check ((\`severity\` in ('error', 'warning')))
)`,
  `create table \`sites\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`key\` varchar(64) not null,
  \`name\` longtext not null,
  \`is_primary\` tinyint(1) not null default 0,
  \`version\` int not null default 1,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`updated_at\` datetime(6) not null default current_timestamp(6),
  unique key \`sites_key_key\` (\`key\`),
  constraint \`sites_pkey\` primary key (\`id\`),
  constraint \`sites_key_check\` check ((regexp_like(\`key\`, '^[a-z][a-z0-9-]{0,62}$', 'c'))),
  constraint \`sites_name_check\` check (((char_length(\`name\`) >= 1) AND (char_length(\`name\`) <= 200)))
)`,
  `create table \`site_app_roles\` (
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`audience\` varchar(64) not null,
  \`role_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  constraint \`site_app_roles_pkey\` primary key (\`site_id\`, \`audience\`, \`role_id\`),
  constraint \`site_app_roles_audience_check\` check ((\`audience\` in ('public', 'authenticated')))
)`,
  `create table \`assist_runs\` (
  \`id\` char(36) character set ascii collate ascii_general_ci not null default (uuid()),
  \`site_id\` char(36) character set ascii collate ascii_general_ci not null,
  \`actor_type\` longtext not null,
  \`actor_id\` longtext not null,
  \`action\` longtext not null,
  \`rule\` longtext,
  \`provider\` longtext not null,
  \`model\` longtext not null,
  \`input_tokens\` int not null default 0,
  \`output_tokens\` int not null default 0,
  \`duration_ms\` int not null default 0,
  \`status\` longtext not null,
  \`error_code\` longtext,
  \`job_id\` char(36) character set ascii collate ascii_general_ci,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  \`finished_at\` datetime(6),
  constraint \`assist_runs_pkey\` primary key (\`id\`),
  constraint \`assist_runs_action_check\` check ((\`action\` in ('alt_text', 'summarize', 'translate', 'rewrite', 'schema_draft', 'content_ops'))),
  constraint \`assist_runs_status_check\` check ((\`status\` in ('queued', 'running', 'succeeded', 'failed')))
)`,
  `alter table \`outbox_events\` add constraint \`outbox_events_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete set null`,
  `alter table \`audit_events\` add constraint \`audit_events_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete set null`,
  `alter table \`admin_role_permissions\` add constraint \`admin_role_permissions_role_id_fkey\` foreign key (\`role_id\`) references \`admin_roles\` (\`id\`) on delete cascade`,
  `alter table \`admin_user_roles\` add constraint \`admin_user_roles_admin_user_id_fkey\` foreign key (\`admin_user_id\`) references \`admin_users\` (\`id\`) on delete cascade`,
  `alter table \`admin_user_roles\` add constraint \`admin_user_roles_role_id_fkey\` foreign key (\`role_id\`) references \`admin_roles\` (\`id\`) on delete restrict`,
  `alter table \`admin_user_roles\` add constraint \`admin_user_roles_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`admin_sessions\` add constraint \`admin_sessions_admin_user_id_fkey\` foreign key (\`admin_user_id\`) references \`admin_users\` (\`id\`) on delete cascade`,
  `alter table \`admin_invitations\` add constraint \`admin_invitations_invited_by_fkey\` foreign key (\`invited_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`password_resets\` add constraint \`password_resets_admin_user_id_fkey\` foreign key (\`admin_user_id\`) references \`admin_users\` (\`id\`) on delete cascade`,
  `alter table \`api_tokens\` add constraint \`api_tokens_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`api_tokens\` add constraint \`api_tokens_role_id_fkey\` foreign key (\`role_id\`) references \`admin_roles\` (\`id\`) on delete restrict`,
  `alter table \`api_tokens\` add constraint \`api_tokens_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`schema_revisions\` add constraint \`schema_revisions_model_id_fkey\` foreign key (\`model_id\`) references \`models\` (\`id\`) on delete restrict`,
  `alter table \`schema_revisions\` add constraint \`schema_revisions_parent_revision_id_fkey\` foreign key (\`parent_revision_id\`) references \`schema_revisions\` (\`id\`)`,
  `alter table \`model_active_versions\` add constraint \`model_active_versions_model_id_fkey\` foreign key (\`model_id\`) references \`models\` (\`id\`) on delete cascade`,
  `alter table \`model_active_versions\` add constraint \`model_active_versions_revision_id_fkey\` foreign key (\`revision_id\`) references \`schema_revisions\` (\`id\`)`,
  `alter table \`schema_change_jobs\` add constraint \`schema_change_jobs_change_set_id_fkey\` foreign key (\`change_set_id\`) references \`change_sets\` (\`id\`) on delete set null`,
  `alter table \`schema_change_jobs\` add constraint \`schema_change_jobs_from_revision_id_fkey\` foreign key (\`from_revision_id\`) references \`schema_revisions\` (\`id\`)`,
  `alter table \`schema_change_jobs\` add constraint \`schema_change_jobs_job_id_fkey\` foreign key (\`job_id\`) references \`jobs\` (\`id\`) on delete set null`,
  `alter table \`schema_change_jobs\` add constraint \`schema_change_jobs_model_id_fkey\` foreign key (\`model_id\`) references \`models\` (\`id\`)`,
  `alter table \`schema_change_jobs\` add constraint \`schema_change_jobs_to_revision_id_fkey\` foreign key (\`to_revision_id\`) references \`schema_revisions\` (\`id\`)`,
  `alter table \`entries\` add constraint \`entries_created_by_admin_id_fkey\` foreign key (\`created_by_admin_id\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`entries\` add constraint \`entries_model_id_fkey\` foreign key (\`model_id\`) references \`models\` (\`id\`) on delete restrict`,
  `alter table \`entries\` add constraint \`entries_owner_app_user_fk\` foreign key (\`owner_app_user_id\`) references \`app_users\` (\`id\`) on delete set null`,
  `alter table \`entries\` add constraint \`entries_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`content_revisions\` add constraint \`content_revisions_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete restrict`,
  `alter table \`content_revisions\` add constraint \`content_revisions_parent_revision_id_fkey\` foreign key (\`parent_revision_id\`) references \`content_revisions\` (\`id\`)`,
  `alter table \`content_revisions\` add constraint \`content_revisions_schema_revision_id_fkey\` foreign key (\`schema_revision_id\`) references \`schema_revisions\` (\`id\`)`,
  `alter table \`entry_heads\` add constraint \`entry_heads_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`entry_heads\` add constraint \`entry_heads_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`entry_heads\` add constraint \`entry_heads_revision_id_fkey\` foreign key (\`revision_id\`) references \`content_revisions\` (\`id\`)`,
  `alter table \`entry_heads\` add constraint \`entry_heads_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`relation_edges\` add constraint \`relation_edges_head_fk\` foreign key (\`source_entry_id\`, \`locale\`, \`state\`) references \`entry_heads\` (\`entry_id\`, \`locale\`, \`state\`) on delete cascade`,
  `alter table \`relation_edges\` add constraint \`relation_edges_target_entry_id_fkey\` foreign key (\`target_entry_id\`) references \`entries\` (\`id\`)`,
  `alter table \`unique_values\` add constraint \`unique_values_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`unique_values\` add constraint \`unique_values_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`unique_values\` add constraint \`unique_values_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`publication_state\` add constraint \`publication_state_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`publication_log\` add constraint \`publication_log_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`)`,
  `alter table \`publication_log\` add constraint \`publication_log_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete restrict`,
  `alter table \`publication_log\` add constraint \`publication_log_revision_id_fkey\` foreign key (\`revision_id\`) references \`content_revisions\` (\`id\`)`,
  `alter table \`publication_log\` add constraint \`publication_log_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`media_folders\` add constraint \`media_folders_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`media_folders\` add constraint \`media_folders_parent_id_fkey\` foreign key (\`parent_id\`, \`site_id\`) references \`media_folders\` (\`id\`, \`site_id\`) on delete restrict`,
  `alter table \`media_folders\` add constraint \`media_folders_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`media_assets\` add constraint \`media_assets_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`media_assets\` add constraint \`media_assets_folder_id_fkey\` foreign key (\`folder_id\`, \`site_id\`) references \`media_folders\` (\`id\`, \`site_id\`)`,
  `alter table \`media_assets\` add constraint \`media_assets_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`media_variants\` add constraint \`media_variants_asset_id_fkey\` foreign key (\`asset_id\`) references \`media_assets\` (\`id\`) on delete cascade`,
  `alter table \`media_references\` add constraint \`media_references_asset_id_fkey\` foreign key (\`asset_id\`) references \`media_assets\` (\`id\`) on delete cascade`,
  `alter table \`media_references\` add constraint \`media_references_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`media_upload_grants\` add constraint \`media_upload_grants_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`media_upload_grants\` add constraint \`media_upload_grants_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`scheduled_publications\` add constraint \`scheduled_publications_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`scheduled_publications\` add constraint \`scheduled_publications_created_by_token_fkey\` foreign key (\`created_by_token\`) references \`api_tokens\` (\`id\`) on delete set null`,
  `alter table \`scheduled_publications\` add constraint \`scheduled_publications_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`scheduled_publications\` add constraint \`scheduled_publications_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`scheduled_publications\` add constraint \`scheduled_publications_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`webhooks\` add constraint \`webhooks_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`webhooks\` add constraint \`webhooks_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`webhook_deliveries\` add constraint \`webhook_deliveries_webhook_id_fkey\` foreign key (\`webhook_id\`) references \`webhooks\` (\`id\`) on delete cascade`,
  `alter table \`deployment_connections\` add constraint \`deployment_connections_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`deployment_connections\` add constraint \`deployment_connections_delivery_role_id_fkey\` foreign key (\`delivery_role_id\`) references \`admin_roles\` (\`id\`) on delete set null`,
  `alter table \`deployment_connections\` add constraint \`deployment_connections_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`deployment_runs\` add constraint \`deployment_runs_change_set_id_fkey\` foreign key (\`change_set_id\`) references \`change_sets\` (\`id\`) on delete set null`,
  `alter table \`deployment_runs\` add constraint \`deployment_runs_connection_id_fkey\` foreign key (\`connection_id\`) references \`deployment_connections\` (\`id\`) on delete cascade`,
  `alter table \`deployment_runs\` add constraint \`deployment_runs_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`deployment_runs\` add constraint \`deployment_runs_retry_of_fkey\` foreign key (\`retry_of\`) references \`deployment_runs\` (\`id\`) on delete set null`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_connection_id_fkey\` foreign key (\`connection_id\`) references \`deployment_connections\` (\`id\`) on delete set null`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete cascade`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_delivery_role_id_fkey\` foreign key (\`delivery_role_id\`) references \`admin_roles\` (\`id\`) on delete set null`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`preview_tokens\` add constraint \`preview_tokens_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`app_users\` add constraint \`app_users_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`app_role_permissions\` add constraint \`app_role_permissions_role_id_fkey\` foreign key (\`role_id\`) references \`app_roles\` (\`id\`) on delete cascade`,
  `alter table \`app_user_roles\` add constraint \`app_user_roles_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`app_user_roles\` add constraint \`app_user_roles_role_id_fkey\` foreign key (\`role_id\`) references \`app_roles\` (\`id\`) on delete restrict`,
  `alter table \`app_user_roles\` add constraint \`app_user_roles_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`app_refresh_tokens\` add constraint \`app_refresh_tokens_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`app_oauth_accounts\` add constraint \`app_oauth_accounts_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`app_oauth_accounts\` add constraint \`app_oauth_accounts_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`email_confirmations\` add constraint \`email_confirmations_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`app_password_resets\` add constraint \`app_password_resets_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`app_login_codes\` add constraint \`app_login_codes_app_user_id_fkey\` foreign key (\`app_user_id\`) references \`app_users\` (\`id\`) on delete cascade`,
  `alter table \`field_reads\` add constraint \`field_reads_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`token_reads\` add constraint \`token_reads_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`change_sets\` add constraint \`change_sets_created_by_fkey\` foreign key (\`created_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_created_by_token_fkey\` foreign key (\`created_by_token\`) references \`api_tokens\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_deployment_connection_id_fkey\` foreign key (\`deployment_connection_id\`) references \`deployment_connections\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_deployment_run_id_fkey\` foreign key (\`deployment_run_id\`) references \`deployment_runs\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_scheduled_by_fkey\` foreign key (\`scheduled_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_scheduled_by_token_fkey\` foreign key (\`scheduled_by_token\`) references \`api_tokens\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_ship_requested_by_fkey\` foreign key (\`ship_requested_by\`) references \`admin_users\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_ship_requested_by_token_fkey\` foreign key (\`ship_requested_by_token\`) references \`api_tokens\` (\`id\`) on delete set null`,
  `alter table \`change_sets\` add constraint \`change_sets_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`schema_drafts\` add constraint \`schema_drafts_change_set_id_fkey\` foreign key (\`change_set_id\`) references \`change_sets\` (\`id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_change_set_id_fkey\` foreign key (\`change_set_id\`) references \`change_sets\` (\`id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_schema_draft_id_fkey\` foreign key (\`schema_draft_id\`) references \`schema_drafts\` (\`id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_set_site_fk\` foreign key (\`change_set_id\`, \`site_id\`) references \`change_sets\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`change_set_items\` add constraint \`change_set_items_source_revision_id_fkey\` foreign key (\`source_revision_id\`) references \`content_revisions\` (\`id\`)`,
  `alter table \`publication_snapshots\` add constraint \`publication_snapshots_change_set_id_fkey\` foreign key (\`change_set_id\`) references \`change_sets\` (\`id\`) on delete set null`,
  `alter table \`publication_snapshots\` add constraint \`publication_snapshots_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`content_health_findings\` add constraint \`content_health_findings_entry_id_fkey\` foreign key (\`entry_id\`) references \`entries\` (\`id\`) on delete cascade`,
  `alter table \`content_health_findings\` add constraint \`content_health_findings_entry_site_fk\` foreign key (\`entry_id\`, \`site_id\`) references \`entries\` (\`id\`, \`site_id\`) on delete cascade`,
  `alter table \`content_health_findings\` add constraint \`content_health_findings_site_fk\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete restrict`,
  `alter table \`site_app_roles\` add constraint \`site_app_roles_role_id_fkey\` foreign key (\`role_id\`) references \`app_roles\` (\`id\`) on delete cascade`,
  `alter table \`site_app_roles\` add constraint \`site_app_roles_site_id_fkey\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `alter table \`assist_runs\` add constraint \`assist_runs_job_id_fkey\` foreign key (\`job_id\`) references \`jobs\` (\`id\`) on delete set null`,
  `alter table \`assist_runs\` add constraint \`assist_runs_site_id_fkey\` foreign key (\`site_id\`) references \`sites\` (\`id\`) on delete cascade`,
  `create index \`admin_invitations_pending_email_idx\` on \`admin_invitations\` (\`email\`)`,
  `create index \`admin_sessions_user_idx\` on \`admin_sessions\` (\`admin_user_id\`)`,
  `create index \`admin_user_roles_role_idx\` on \`admin_user_roles\` (\`role_id\`)`,
  `create index \`api_tokens_role_idx\` on \`api_tokens\` (\`role_id\`)`,
  `create index \`app_oauth_accounts_user_idx\` on \`app_oauth_accounts\` (\`app_user_id\`)`,
  `create index \`app_password_resets_user_idx\` on \`app_password_resets\` (\`app_user_id\`)`,
  `create index \`app_refresh_tokens_family_idx\` on \`app_refresh_tokens\` (\`family_id\`)`,
  `create index \`app_refresh_tokens_user_idx\` on \`app_refresh_tokens\` (\`app_user_id\`)`,
  `create index \`app_user_roles_role_idx\` on \`app_user_roles\` (\`role_id\`)`,
  `create index \`app_users_created_idx\` on \`app_users\` (\`site_id\`, \`created_at\` desc, \`id\` desc)`,
  `create unique index \`app_users_email_uq\` on \`app_users\` ((case when (\`deleted_at\` IS NULL) then \`site_id\` end), (case when (\`deleted_at\` IS NULL) then lower(\`email\`) end))`,
  `create index \`assist_runs_created_idx\` on \`assist_runs\` (\`created_at\`)`,
  `create index \`assist_runs_site_created_idx\` on \`assist_runs\` (\`site_id\`, \`created_at\`)`,
  `create index \`audit_events_actor_idx\` on \`audit_events\` (\`actor_type\`, \`actor_id\`, \`occurred_at\` desc)`,
  `create index \`audit_events_occurred_at_idx\` on \`audit_events\` (\`occurred_at\` desc)`,
  `create index \`audit_events_target_idx\` on \`audit_events\` (\`target_type\`, \`target_id\`, \`occurred_at\` desc)`,
  `create unique index \`change_set_items_draft_uq\` on \`change_set_items\` (\`schema_draft_id\`)`,
  `create index \`change_set_items_entry_idx\` on \`change_set_items\` (\`entry_id\`)`,
  `create unique index \`change_set_items_entry_uq\` on \`change_set_items\` ((case when (\`kind\` = 'entry') then \`change_set_id\` end), (case when (\`kind\` = 'entry') then \`entry_id\` end), (case when (\`kind\` = 'entry') then \`locale\` end))`,
  `create index \`change_set_items_set_idx\` on \`change_set_items\` (\`change_set_id\`, \`position\`)`,
  `create index \`change_sets_status_idx\` on \`change_sets\` (\`site_id\`, \`status\`, \`created_at\` desc)`,
  `create index \`content_health_findings_open_idx\` on \`content_health_findings\` (\`site_id\`, \`rule\`, \`last_seen_at\` desc, \`id\`)`,
  `create index \`content_health_findings_resolved_idx\` on \`content_health_findings\` (\`resolved_at\`)`,
  `create index \`content_revisions_entry_idx\` on \`content_revisions\` (\`entry_id\`, \`locale\`, \`created_at\`)`,
  `create index \`deployment_runs_connection_idx\` on \`deployment_runs\` (\`connection_id\`, \`created_at\` desc)`,
  `create unique index \`deployment_runs_queued_uq\` on \`deployment_runs\` ((case when (\`status\` = 'queued') then \`connection_id\` end))`,
  `create index \`editor_presence_model_idx\` on \`editor_presence\` (\`model_id\`, \`last_seen_at\`)`,
  `create index \`editor_presence_seen_idx\` on \`editor_presence\` (\`last_seen_at\`)`,
  `create index \`email_confirmations_user_idx\` on \`email_confirmations\` (\`app_user_id\`)`,
  `create index \`entries_model_idx\` on \`entries\` (\`site_id\`, \`model_id\`, \`created_at\`)`,
  `create index \`entries_owner_idx\` on \`entries\` (\`owner_app_user_id\`)`,
  `create index \`entry_heads_change_seq_idx\` on \`entry_heads\` (\`model_id\`, \`change_seq\`)`,
  `create index \`entry_heads_model_locale_state_idx\` on \`entry_heads\` (\`site_id\`, \`model_id\`, \`locale\`, \`state\`)`,
  `create index \`field_reads_model_day_idx\` on \`field_reads\` (\`model_id\`, \`day\`)`,
  `create unique index \`jobs_idempotency_key_uq\` on \`jobs\` (\`idempotency_key\`)`,
  `create index \`jobs_pending_idx\` on \`jobs\` (\`priority\` desc, \`run_at\`)`,
  `create index \`jobs_running_lease_idx\` on \`jobs\` (\`locked_until\`)`,
  `create unique index \`locales_single_default_uq\` on \`locales\` ((case when \`is_default\` then \`is_default\` end))`,
  `create index \`media_assets_created_idx\` on \`media_assets\` (\`site_id\`, \`created_at\`, \`id\`)`,
  `create index \`media_assets_driver_idx\` on \`media_assets\` (\`storage_driver\`, \`id\`)`,
  `create index \`media_assets_folder_idx\` on \`media_assets\` (\`folder_id\`, \`created_at\`, \`id\`)`,
  `create unique index \`media_assets_storage_key_uq\` on \`media_assets\` (\`storage_key\`)`,
  `create unique index \`media_folders_sibling_name_uq\` on \`media_folders\` (\`site_id\`, (COALESCE(\`parent_id\`, '00000000-0000-0000-0000-000000000000')), (lower(\`name\`)))`,
  `create index \`media_references_entry_idx\` on \`media_references\` (\`entry_id\`, \`locale\`, \`state\`)`,
  `create unique index \`media_variants_storage_key_uq\` on \`media_variants\` (\`storage_key\`)`,
  `create unique index \`models_api_key_uq\` on \`models\` ((case when (\`deleted_at\` IS NULL) then lower(\`api_key\`) end))`,
  `create index \`outbox_events_undispatched_idx\` on \`outbox_events\` (\`id\`)`,
  `create index \`password_resets_user_idx\` on \`password_resets\` (\`admin_user_id\`)`,
  `create index \`preview_tokens_entry_idx\` on \`preview_tokens\` (\`entry_id\`, \`created_at\` desc)`,
  `create index \`publication_log_entry_locale_from_idx\` on \`publication_log\` (\`entry_id\`, \`locale\`, \`from_seq\`)`,
  `create index \`publication_log_model_seq_idx\` on \`publication_log\` (\`site_id\`, \`model_id\`, \`from_seq\`)`,
  `create unique index \`publication_log_open_uq\` on \`publication_log\` ((case when (\`to_seq\` IS NULL) then \`entry_id\` end), (case when (\`to_seq\` IS NULL) then \`locale\` end))`,
  `create index \`publication_log_to_seq_idx\` on \`publication_log\` (\`site_id\`, \`to_seq\`)`,
  `create index \`publication_snapshots_change_set_idx\` on \`publication_snapshots\` (\`change_set_id\`)`,
  `create index \`relation_edges_target_idx\` on \`relation_edges\` (\`target_entry_id\`, \`state\`)`,
  `create index \`scheduled_publications_entry_idx\` on \`scheduled_publications\` (\`entry_id\`, \`locale\`)`,
  `create index \`scheduled_publications_site_idx\` on \`scheduled_publications\` (\`site_id\`, \`run_at\`)`,
  `create index \`scheduled_publications_status_idx\` on \`scheduled_publications\` (\`status\`, \`run_at\`)`,
  `create index \`schema_change_jobs_change_set_idx\` on \`schema_change_jobs\` (\`change_set_id\`)`,
  `create unique index \`schema_change_jobs_in_flight_uq\` on \`schema_change_jobs\` ((case when (\`status\` in ('pending', 'running')) then \`target_type\` end), (case when (\`status\` in ('pending', 'running')) then \`target_id\` end))`,
  `create index \`schema_change_jobs_model_idx\` on \`schema_change_jobs\` (\`model_id\`, \`created_at\` desc)`,
  `create index \`schema_drafts_definition_idx\` on \`schema_drafts\` (\`definition_id\`)`,
  `create index \`site_app_roles_role_idx\` on \`site_app_roles\` (\`role_id\`)`,
  `create unique index \`sites_single_primary_uq\` on \`sites\` ((case when \`is_primary\` then \`is_primary\` end))`,
  `create index \`unique_values_entry_idx\` on \`unique_values\` (\`entry_id\`)`,
  `create unique index \`webhook_deliveries_event_uq\` on \`webhook_deliveries\` (\`webhook_id\`, \`event_id\`)`,
  `create index \`webhook_deliveries_webhook_idx\` on \`webhook_deliveries\` (\`webhook_id\`, \`created_at\` desc)`,
  `create table \`advisory_locks\` (
  \`namespace\` int not null,
  \`lock_key\` int not null,
  constraint \`advisory_locks_pkey\` primary key (\`namespace\`, \`lock_key\`)
)`,
  `create table \`notifications\` (
  \`id\` bigint not null auto_increment,
  \`channel\` varchar(64) not null,
  \`payload\` longtext not null,
  \`created_at\` datetime(6) not null default current_timestamp(6),
  constraint \`notifications_pkey\` primary key (\`id\`)
)`,
  `create index \`notifications_created_idx\` on \`notifications\` (\`created_at\`)`,
  `create table \`sequence_entry_heads_change_seq\` (
  \`value\` bigint not null auto_increment,
  constraint \`sequence_entry_heads_change_seq_pkey\` primary key (\`value\`)
)`,
  `create trigger \`media_assets_folder_id_fkey_set_null\` before delete on \`media_folders\` for each row
  update \`media_assets\` set \`folder_id\` = null where \`folder_id\` = old.\`id\` and \`site_id\` = old.\`site_id\``,
  `create trigger \`schema_revisions_no_update\` before update on \`schema_revisions\` for each row
  signal sqlstate '45000' set message_text = 'schema_revisions rows are immutable'`,
  `create trigger \`content_revisions_no_update\` before update on \`content_revisions\` for each row
  signal sqlstate '45000' set message_text = 'content_revisions rows are immutable'`,
  `insert into \`system_versions\` () values ()`,
  `insert into \`schema_settings\` () values ()`,
  `insert into \`locales\` (\`code\`, \`label\`, \`is_default\`) values ('en', 'English', 1)`,
  `insert into \`sites\` (\`id\`, \`key\`, \`name\`, \`is_primary\`) values ('00000000-0000-4000-b000-000000000001', 'default', 'Default site', 1)`,
  `insert into \`publication_state\` (\`site_id\`, \`last_seq\`) values ('00000000-0000-4000-b000-000000000001', 0)`,
  `insert into \`app_roles\` (\`id\`, \`key\`, \`name\`, \`description\`, \`is_system\`) values
    ('00000000-0000-4000-a000-000000000001', 'public', 'Public', 'Applies to every caller without a token. Grants nothing until you add permissions.', 1),
    ('00000000-0000-4000-a000-000000000002', 'authenticated', 'Authenticated', 'Held by every signed-in app user, in addition to their custom roles. Grants nothing until you add permissions.', 1)`,
  `insert into \`site_app_roles\` (\`site_id\`, \`audience\`, \`role_id\`) values
    ('00000000-0000-4000-b000-000000000001', 'public', '00000000-0000-4000-a000-000000000001'),
    ('00000000-0000-4000-b000-000000000001', 'authenticated', '00000000-0000-4000-a000-000000000002')`,
];

const TABLES: readonly string[] = [
  'system_versions',
  'jobs',
  'outbox_events',
  'audit_events',
  'admin_users',
  'admin_roles',
  'admin_role_permissions',
  'admin_user_roles',
  'admin_sessions',
  'admin_invitations',
  'password_resets',
  'setup_tokens',
  'api_tokens',
  'system_settings',
  'models',
  'schema_revisions',
  'model_active_versions',
  'schema_change_jobs',
  'locales',
  'schema_settings',
  'entries',
  'content_revisions',
  'entry_heads',
  'relation_edges',
  'unique_values',
  'publication_state',
  'publication_log',
  'media_folders',
  'media_assets',
  'media_variants',
  'media_references',
  'media_upload_grants',
  'scheduled_publications',
  'webhooks',
  'webhook_deliveries',
  'deployment_connections',
  'deployment_runs',
  'preview_tokens',
  'app_users',
  'app_roles',
  'app_role_permissions',
  'app_user_roles',
  'app_refresh_tokens',
  'app_oauth_accounts',
  'email_confirmations',
  'app_password_resets',
  'app_login_codes',
  'extension_hook_runs',
  'field_reads',
  'token_reads',
  'change_sets',
  'schema_drafts',
  'change_set_items',
  'publication_snapshots',
  'editor_presence',
  'content_health_findings',
  'sites',
  'site_app_roles',
  'assist_runs',
  'advisory_locks',
  'notifications',
  'sequence_entry_heads_change_seq',
];

/** Runs the statements on one connection, where `foreign_key_checks` is off (tables reference in cycles). */
const withoutForeignKeyChecks = async (db: Kysely<unknown>, statements: readonly string[]) =>
  db.connection().execute(async (connection) => {
    await sql`set foreign_key_checks = 0`.execute(connection);
    try {
      for (const statement of statements) {
        await sql.raw(statement).execute(connection);
      }
    } finally {
      await sql`set foreign_key_checks = 1`.execute(connection);
    }
  });

export const up = async (db: Kysely<unknown>): Promise<void> => withoutForeignKeyChecks(db, STATEMENTS);

export const down = async (db: Kysely<unknown>): Promise<void> =>
  withoutForeignKeyChecks(
    db,
    [...TABLES].reverse().map((table) => `drop table if exists \`${table}\``),
  );
